param(
    [string]$Action = "pre-commit",
    [string]$Branch = "",
    [switch]$Quiet
)

$ErrorActionPreference = "Stop"

function Resolve-ProjectRoot {
    $dir = $PSScriptRoot
    for ($i = 0; $i -lt 8; $i++) {
        if (Test-Path (Join-Path $dir ".git")) { return $dir }
        $parent = Split-Path $dir -Parent
        if (-not $parent -or $parent -eq $dir) { break }
        $dir = $parent
    }
    return $PSScriptRoot
}

$ProjectRoot = Resolve-ProjectRoot
$DiagramScript = Join-Path $PSScriptRoot "codegraph-diagram.ps1"
$DiagramDir = Join-Path $ProjectRoot "docs\diagrams"
$DocsDir = Join-Path $ProjectRoot "docs"

function Get-PrBranch {
    if ($Branch) { return $Branch }
    try {
        $b = git -C $ProjectRoot rev-parse --abbrev-ref HEAD 2>$null
        if ($b) { return $b.Trim() }
    } catch { Write-Debug "Exception caught: param(
    [string]$Action = "pre-commit",
    [string]$Branch = "",
    [switch]$Quiet
)

$ErrorActionPreference = "Stop"

function Resolve-ProjectRoot {
    $dir = $PSScriptRoot
    for ($i = 0; $i -lt 8; $i++) {
        if (Test-Path (Join-Path $dir ".git")) { return $dir }
        $parent = Split-Path $dir -Parent
        if (-not $parent -or $parent -eq $dir) { break }
        $dir = $parent
    }
    return $PSScriptRoot
}

$ProjectRoot = Resolve-ProjectRoot
$DiagramScript = Join-Path $PSScriptRoot "codegraph-diagram.ps1"
$DiagramDir = Join-Path $ProjectRoot "docs\diagrams"
$DocsDir = Join-Path $ProjectRoot "docs"

function Get-PrBranch {
    if ($Branch) { return $Branch }
    try {
        $b = git -C $ProjectRoot rev-parse --abbrev-ref HEAD 2>$null
        if ($b) { return $b.Trim() }
    } catch { Write-Debug "Exception caught: param(
    [string]$Action = "pre-commit",
    [string]$Branch = "",
    [switch]$Quiet
)

$ErrorActionPreference = "Stop"

function Resolve-ProjectRoot {
    $dir = $PSScriptRoot
    for ($i = 0; $i -lt 8; $i++) {
        if (Test-Path (Join-Path $dir ".git")) { return $dir }
        $parent = Split-Path $dir -Parent
        if (-not $parent -or $parent -eq $dir) { break }
        $dir = $parent
    }
    return $PSScriptRoot
}

$ProjectRoot = Resolve-ProjectRoot
$DiagramScript = Join-Path $PSScriptRoot "codegraph-diagram.ps1"
$DiagramDir = Join-Path $ProjectRoot "docs\diagrams"
$DocsDir = Join-Path $ProjectRoot "docs"

function Get-PrBranch {
    if ($Branch) { return $Branch }
    try {
        $b = git -C $ProjectRoot rev-parse --abbrev-ref HEAD 2>$null
        if ($b) { return $b.Trim() }
    } catch { Write-Debug "Exception caught: param(
    [string]$Action = "pre-commit",
    [string]$Branch = "",
    [switch]$Quiet
)

$ErrorActionPreference = "Stop"

function Resolve-ProjectRoot {
    $dir = $PSScriptRoot
    for ($i = 0; $i -lt 8; $i++) {
        if (Test-Path (Join-Path $dir ".git")) { return $dir }
        $parent = Split-Path $dir -Parent
        if (-not $parent -or $parent -eq $dir) { break }
        $dir = $parent
    }
    return $PSScriptRoot
}

$ProjectRoot = Resolve-ProjectRoot
$DiagramScript = Join-Path $PSScriptRoot "codegraph-diagram.ps1"
$DiagramDir = Join-Path $ProjectRoot "docs\diagrams"
$DocsDir = Join-Path $ProjectRoot "docs"

function Get-PrBranch {
    if ($Branch) { return $Branch }
    try {
        $b = git -C $ProjectRoot rev-parse --abbrev-ref HEAD 2>$null
        if ($b) { return $b.Trim() }
    } catch { Write-Output "[PR-DOCS] Operation failed, continuing" }
    return ""
}

function Update-ArchitectureDoc {
    $archDoc = Join-Path $DocsDir "architecture.md"
    $diagrams = Get-ChildItem -Path $DiagramDir -Filter "*.mmd" -ErrorAction SilentlyContinue | Sort-Object Name
    if ($diagrams.Count -eq 0) {
        if (-not $Quiet) { Write-Warning "No diagrams found in $DiagramDir" }
        return $false
    }
    $content = @"
# Architecture Documentation

*Auto-generated by pr-docs-hook.ps1 | Last updated: $(Get-Date -Format 'yyyy-MM-dd HH:mm')*

## Module Dependencies

\`\`\`mermaid
$(Get-Content (Join-Path $DiagramDir "module-dependency.mmd") -Raw 2>$null)
\`\`\`

## Call Graph

\`\`\`mermaid
$(Get-Content (Join-Path $DiagramDir "call-graph.mmd") -Raw 2>$null)
\`\`\`

## Data Flow

\`\`\`mermaid
$(Get-Content (Join-Path $DiagramDir "data-flow.mmd") -Raw 2>$null)
\`\`\`

---
*Diagrams regenerated on every PR to reflect current codebase state.*
"@
    $content | Set-Content -Path $archDoc -Encoding UTF8
    if (-not $Quiet) { Write-Host "[DOC] Updated $archDoc" -ForegroundColor Green }
    return $true
}

if ($Action -eq "pre-commit") {
    $branch = Get-PrBranch
    if ($branch -match '^(main|master|develop)$') {
        if (-not $Quiet) { Write-Host "[SKIP] No diagram regeneration on $branch branch" -ForegroundColor DarkGray }
        exit 0
    }
    if (-not (Test-Path $DiagramScript)) {
        Write-Error "codegraph-diagram.ps1 not found at $DiagramScript"
        exit 1
    }
    & $DiagramScript -DiagramType all -OutputDir $DiagramDir 2>&1 | Out-Null
    Update-ArchitectureDoc
    if (-not $Quiet) { Write-Host "[PR-DOCS] Architecture diagrams updated for branch: $branch" -ForegroundColor Cyan }
    exit 0
}

if ($Action -eq "post-merge") {
    & $DiagramScript -DiagramType all -OutputDir $DiagramDir 2>&1 | Out-Null
    Update-ArchitectureDoc
    if (-not $Quiet) { Write-Host "[PR-DOCS] Architecture diagrams regenerated post-merge" -ForegroundColor Cyan }
    exit 0
}

if ($Action -eq "status") {
    $diagrams = Get-ChildItem -Path $DiagramDir -Filter "*.mmd" -ErrorAction SilentlyContinue
    $archDoc = Join-Path $DocsDir "architecture.md"
    Write-Host "=== Architecture Documentation Status ===" -ForegroundColor Cyan
    Write-Host "Diagrams: $($diagrams.Count) files" -ForegroundColor $(if ($diagrams.Count -ge 3) { "Green" } else { "Yellow" })
    foreach ($d in $diagrams) { Write-Host "  $($d.Name) ($([Math]::Round($d.Length/1KB)) KB)" -ForegroundColor DarkGray }
    Write-Host "Arch doc: $(if (Test-Path $archDoc) { 'EXISTS' } else { 'MISSING' })" -ForegroundColor $(if (Test-Path $archDoc) { "Green" } else { "Red" })
    exit 0
}

Write-Host "Usage: pr-docs-hook.ps1 -Action <pre-commit|post-merge|status> [-Branch <name>] [-Quiet]" -ForegroundColor Yellow
exit 1
" }
    return ""
}

function Update-ArchitectureDoc {
    $archDoc = Join-Path $DocsDir "architecture.md"
    $diagrams = Get-ChildItem -Path $DiagramDir -Filter "*.mmd" -ErrorAction SilentlyContinue | Sort-Object Name
    if ($diagrams.Count -eq 0) {
        if (-not $Quiet) { Write-Warning "No diagrams found in $DiagramDir" }
        return $false
    }
    $content = @"
# Architecture Documentation

*Auto-generated by pr-docs-hook.ps1 | Last updated: $(Get-Date -Format 'yyyy-MM-dd HH:mm')*

## Module Dependencies

\`\`\`mermaid
$(Get-Content (Join-Path $DiagramDir "module-dependency.mmd") -Raw 2>$null)
\`\`\`

## Call Graph

\`\`\`mermaid
$(Get-Content (Join-Path $DiagramDir "call-graph.mmd") -Raw 2>$null)
\`\`\`

## Data Flow

\`\`\`mermaid
$(Get-Content (Join-Path $DiagramDir "data-flow.mmd") -Raw 2>$null)
\`\`\`

---
*Diagrams regenerated on every PR to reflect current codebase state.*
"@
    $content | Set-Content -Path $archDoc -Encoding UTF8
    if (-not $Quiet) { Write-Host "[DOC] Updated $archDoc" -ForegroundColor Green }
    return $true
}

if ($Action -eq "pre-commit") {
    $branch = Get-PrBranch
    if ($branch -match '^(main|master|develop)$') {
        if (-not $Quiet) { Write-Host "[SKIP] No diagram regeneration on $branch branch" -ForegroundColor DarkGray }
        exit 0
    }
    if (-not (Test-Path $DiagramScript)) {
        Write-Error "codegraph-diagram.ps1 not found at $DiagramScript"
        exit 1
    }
    & $DiagramScript -DiagramType all -OutputDir $DiagramDir 2>&1 | Out-Null
    Update-ArchitectureDoc
    if (-not $Quiet) { Write-Host "[PR-DOCS] Architecture diagrams updated for branch: $branch" -ForegroundColor Cyan }
    exit 0
}

if ($Action -eq "post-merge") {
    & $DiagramScript -DiagramType all -OutputDir $DiagramDir 2>&1 | Out-Null
    Update-ArchitectureDoc
    if (-not $Quiet) { Write-Host "[PR-DOCS] Architecture diagrams regenerated post-merge" -ForegroundColor Cyan }
    exit 0
}

if ($Action -eq "status") {
    $diagrams = Get-ChildItem -Path $DiagramDir -Filter "*.mmd" -ErrorAction SilentlyContinue
    $archDoc = Join-Path $DocsDir "architecture.md"
    Write-Host "=== Architecture Documentation Status ===" -ForegroundColor Cyan
    Write-Host "Diagrams: $($diagrams.Count) files" -ForegroundColor $(if ($diagrams.Count -ge 3) { "Green" } else { "Yellow" })
    foreach ($d in $diagrams) { Write-Host "  $($d.Name) ($([Math]::Round($d.Length/1KB)) KB)" -ForegroundColor DarkGray }
    Write-Host "Arch doc: $(if (Test-Path $archDoc) { 'EXISTS' } else { 'MISSING' })" -ForegroundColor $(if (Test-Path $archDoc) { "Green" } else { "Red" })
    exit 0
}

Write-Host "Usage: pr-docs-hook.ps1 -Action <pre-commit|post-merge|status> [-Branch <name>] [-Quiet]" -ForegroundColor Yellow
exit 1

" }
    return ""
}

function Update-ArchitectureDoc {
    $archDoc = Join-Path $DocsDir "architecture.md"
    $diagrams = Get-ChildItem -Path $DiagramDir -Filter "*.mmd" -ErrorAction SilentlyContinue | Sort-Object Name
    if ($diagrams.Count -eq 0) {
        if (-not $Quiet) { Write-Warning "No diagrams found in $DiagramDir" }
        return $false
    }
    $content = @"
# Architecture Documentation

*Auto-generated by pr-docs-hook.ps1 | Last updated: $(Get-Date -Format 'yyyy-MM-dd HH:mm')*

## Module Dependencies

\`\`\`mermaid
$(Get-Content (Join-Path $DiagramDir "module-dependency.mmd") -Raw 2>$null)
\`\`\`

## Call Graph

\`\`\`mermaid
$(Get-Content (Join-Path $DiagramDir "call-graph.mmd") -Raw 2>$null)
\`\`\`

## Data Flow

\`\`\`mermaid
$(Get-Content (Join-Path $DiagramDir "data-flow.mmd") -Raw 2>$null)
\`\`\`

---
*Diagrams regenerated on every PR to reflect current codebase state.*
"@
    $content | Set-Content -Path $archDoc -Encoding UTF8
    if (-not $Quiet) { Write-Host "[DOC] Updated $archDoc" -ForegroundColor Green }
    return $true
}

if ($Action -eq "pre-commit") {
    $branch = Get-PrBranch
    if ($branch -match '^(main|master|develop)$') {
        if (-not $Quiet) { Write-Host "[SKIP] No diagram regeneration on $branch branch" -ForegroundColor DarkGray }
        exit 0
    }
    if (-not (Test-Path $DiagramScript)) {
        Write-Error "codegraph-diagram.ps1 not found at $DiagramScript"
        exit 1
    }
    & $DiagramScript -DiagramType all -OutputDir $DiagramDir 2>&1 | Out-Null
    Update-ArchitectureDoc
    if (-not $Quiet) { Write-Host "[PR-DOCS] Architecture diagrams updated for branch: $branch" -ForegroundColor Cyan }
    exit 0
}

if ($Action -eq "post-merge") {
    & $DiagramScript -DiagramType all -OutputDir $DiagramDir 2>&1 | Out-Null
    Update-ArchitectureDoc
    if (-not $Quiet) { Write-Host "[PR-DOCS] Architecture diagrams regenerated post-merge" -ForegroundColor Cyan }
    exit 0
}

if ($Action -eq "status") {
    $diagrams = Get-ChildItem -Path $DiagramDir -Filter "*.mmd" -ErrorAction SilentlyContinue
    $archDoc = Join-Path $DocsDir "architecture.md"
    Write-Host "=== Architecture Documentation Status ===" -ForegroundColor Cyan
    Write-Host "Diagrams: $($diagrams.Count) files" -ForegroundColor $(if ($diagrams.Count -ge 3) { "Green" } else { "Yellow" })
    foreach ($d in $diagrams) { Write-Host "  $($d.Name) ($([Math]::Round($d.Length/1KB)) KB)" -ForegroundColor DarkGray }
    Write-Host "Arch doc: $(if (Test-Path $archDoc) { 'EXISTS' } else { 'MISSING' })" -ForegroundColor $(if (Test-Path $archDoc) { "Green" } else { "Red" })
    exit 0
}

Write-Host "Usage: pr-docs-hook.ps1 -Action <pre-commit|post-merge|status> [-Branch <name>] [-Quiet]" -ForegroundColor Yellow
exit 1
" }
    return ""
}

function Update-ArchitectureDoc {
    $archDoc = Join-Path $DocsDir "architecture.md"
    $diagrams = Get-ChildItem -Path $DiagramDir -Filter "*.mmd" -ErrorAction SilentlyContinue | Sort-Object Name
    if ($diagrams.Count -eq 0) {
        if (-not $Quiet) { Write-Warning "No diagrams found in $DiagramDir" }
        return $false
    }
    $content = @"
# Architecture Documentation

*Auto-generated by pr-docs-hook.ps1 | Last updated: $(Get-Date -Format 'yyyy-MM-dd HH:mm')*

## Module Dependencies

\`\`\`mermaid
$(Get-Content (Join-Path $DiagramDir "module-dependency.mmd") -Raw 2>$null)
\`\`\`

## Call Graph

\`\`\`mermaid
$(Get-Content (Join-Path $DiagramDir "call-graph.mmd") -Raw 2>$null)
\`\`\`

## Data Flow

\`\`\`mermaid
$(Get-Content (Join-Path $DiagramDir "data-flow.mmd") -Raw 2>$null)
\`\`\`

---
*Diagrams regenerated on every PR to reflect current codebase state.*
"@
    $content | Set-Content -Path $archDoc -Encoding UTF8
    if (-not $Quiet) { Write-Host "[DOC] Updated $archDoc" -ForegroundColor Green }
    return $true
}

if ($Action -eq "pre-commit") {
    $branch = Get-PrBranch
    if ($branch -match '^(main|master|develop)$') {
        if (-not $Quiet) { Write-Host "[SKIP] No diagram regeneration on $branch branch" -ForegroundColor DarkGray }
        exit 0
    }
    if (-not (Test-Path $DiagramScript)) {
        Write-Error "codegraph-diagram.ps1 not found at $DiagramScript"
        exit 1
    }
    & $DiagramScript -DiagramType all -OutputDir $DiagramDir 2>&1 | Out-Null
    Update-ArchitectureDoc
    if (-not $Quiet) { Write-Host "[PR-DOCS] Architecture diagrams updated for branch: $branch" -ForegroundColor Cyan }
    exit 0
}

if ($Action -eq "post-merge") {
    & $DiagramScript -DiagramType all -OutputDir $DiagramDir 2>&1 | Out-Null
    Update-ArchitectureDoc
    if (-not $Quiet) { Write-Host "[PR-DOCS] Architecture diagrams regenerated post-merge" -ForegroundColor Cyan }
    exit 0
}

if ($Action -eq "status") {
    $diagrams = Get-ChildItem -Path $DiagramDir -Filter "*.mmd" -ErrorAction SilentlyContinue
    $archDoc = Join-Path $DocsDir "architecture.md"
    Write-Host "=== Architecture Documentation Status ===" -ForegroundColor Cyan
    Write-Host "Diagrams: $($diagrams.Count) files" -ForegroundColor $(if ($diagrams.Count -ge 3) { "Green" } else { "Yellow" })
    foreach ($d in $diagrams) { Write-Host "  $($d.Name) ($([Math]::Round($d.Length/1KB)) KB)" -ForegroundColor DarkGray }
    Write-Host "Arch doc: $(if (Test-Path $archDoc) { 'EXISTS' } else { 'MISSING' })" -ForegroundColor $(if (Test-Path $archDoc) { "Green" } else { "Red" })
    exit 0
}

Write-Host "Usage: pr-docs-hook.ps1 -Action <pre-commit|post-merge|status> [-Branch <name>] [-Quiet]" -ForegroundColor Yellow
exit 1


