<#
.SYNOPSIS
    Auto-escalation: Create GitHub issues when benchmark failures repeat.

.DESCRIPTION
    Tracks benchmark failure count and creates GitHub issues for operational escalation:
    - 3+ consecutive failures → auto-create issue with incident details
    - Includes remediation log, trace, and suggested fixes
    - Links to incident report from local playbook

.PARAMETER Repository
    GitHub repo in format "owner/repo" (e.g., "my-org/foundation")

.PARAMETER GitHubToken
    GitHub Personal Access Token (read from env:GITHUB_TOKEN if not provided)

.PARAMETER FailureCount
    Current consecutive failure count

.PARAMETER IncidentDetails
    Hashtable with failure context (latency, routing accuracy, layers failed, etc.)

.PARAMETER IncidentReportPath
    Path to local incident report markdown file

.PARAMETER DashboardUrl
    URL to live dashboard for issue link

.PARAMETER FailureThreshold
    Number of failures before auto-create. Default: 3

.PARAMETER DryRun
    Don't create issue, just show what would be created

.EXAMPLE
    .\\auto-escalation.ps1 -Repository "my-org/foundation" -FailureCount 3 `
        -IncidentDetails @{latency_delta="35%"; routing_accuracy=92} `
        -IncidentReportPath "./reports/incidents/stack-benchmark-remediation-2026-05-13-190927.md"
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$Repository,

    [string]$GitHubToken = $env:GITHUB_TOKEN,

    [Parameter(Mandatory=$true)]
    [int]$FailureCount,

    [hashtable]$IncidentDetails = @{},

    [string]$IncidentReportPath = '',

    [string]$DashboardUrl = 'http://localhost:8090/dashboard.html',

    [int]$FailureThreshold = 3,

    [switch]$DryRun
)

$ErrorActionPreference = 'Continue'

if (-not $GitHubToken) {
    Write-Host "[WARN] GITHUB_TOKEN not set, skipping auto-escalation" -ForegroundColor Yellow
    exit 0
}

if ($FailureCount -lt $FailureThreshold) {
    Write-Host "[INFO] Failure count ($FailureCount) below threshold ($FailureThreshold), no escalation" -ForegroundColor Gray
    exit 0
}

# Build issue body
$incidentContent = ""
if ($IncidentReportPath -and (Test-Path $IncidentReportPath)) {
    $incidentContent = Get-Content $IncidentReportPath -Raw
}

$createdAtUtc = (Get-Date).ToUniversalTime().ToString('yyyy-MM-dd HH:mm:ss')

$issueBody = @"
## 🔴 Auto-Escalated Incident

**Consecutive Failures**: $FailureCount (threshold: $FailureThreshold)  
**Created**: $createdAtUtc UTC  
**Dashboard**: [$DashboardUrl]($DashboardUrl)

### Details
"@

foreach ($key in $IncidentDetails.Keys) {
    $issueBody += "`n- **$(($key -replace '_', ' ') | ForEach-Object { (Get-Culture).TextInfo.ToTitleCase($_) })**: $($IncidentDetails[$key])"
}

if ($incidentContent) {
    $issueBody += "`n`n### Incident Report`n`n```markdown`n$incidentContent`n```n"
}

$issueBody += @"

### Suggested Actions

1. **Review Dashboard**: Open [live dashboard]($DashboardUrl) for real-time metrics
2. **Check Logs**: `cat reports/incidents/stack-benchmark-remediation-*.md`
3. **Run Diagnostics**: `foundation health` / `foundation benchmark full`
4. **Auto-Fix Attempt**: `foundation benchmark full remediate`
5. **Escalate**: If manual investigation needed, contact on-call

---
*Generated by Foundation auto-escalation system*
"@

$issueTitle = "🔴 Stack Benchmark Failure — Auto-Escalated ($($FailureCount) failures)"

if ($DryRun) {
    Write-Host "=== DRY RUN: GitHub Issue Auto-Escalation ===" -ForegroundColor Cyan
    Write-Host "Repo:   $Repository" -ForegroundColor Gray
    Write-Host "Title:  $issueTitle" -ForegroundColor Gray
    Write-Host "Labels: incident, auto-escalation, benchmark" -ForegroundColor Gray
    Write-Host ""
    Write-Host "Body:" -ForegroundColor Gray
    Write-Host $issueBody -ForegroundColor Gray
    exit 0
}

# GitHub API call
$headers = @{
    'Authorization' = "token $GitHubToken"
    'Accept'        = 'application/vnd.github.v3+json'
    'User-Agent'    = 'Foundation-AutoEscalation/1.0'
}

$payload = @{
    title  = $issueTitle
    body   = $issueBody
    labels = @('incident', 'auto-escalation', 'benchmark')
} | ConvertTo-Json

$apiUrl = "https://api.github.com/repos/$Repository/issues"

try {
    $response = Invoke-WebRequest -Uri $apiUrl `
        -Method POST `
        -Headers $headers `
        -Body $payload `
        -ContentType 'application/json' `
        -TimeoutSec 10 `
        -ErrorAction Stop

    $issue = $response.Content | ConvertFrom-Json
    Write-Host "[OK] GitHub issue created: #$($issue.number)" -ForegroundColor Green
    Write-Host "     URL: $($issue.html_url)" -ForegroundColor Green
    exit 0
} catch {
    Write-Host "[ERROR] GitHub API failed: $($_.Exception.Message)" -ForegroundColor Red
    exit 2
}
