const i18n = {
  currentLang: localStorage.getItem('gv-lang') || 'en',
  init() {
    const savedLang = localStorage.getItem('gv-lang');
    if (!savedLang) { localStorage.setItem('gv-lang', 'en'); this.currentLang = 'en'; }
    else { this.currentLang = savedLang; }
    document.documentElement.lang = this.currentLang;
  },
  t(key) {
    const keys = key.split('.');
    let value = this.translations[this.currentLang];
    for (const k of keys) { value = value?.[k]; }
    return value || key;
  },
  setLang(lang) {
    this.currentLang = lang; localStorage.setItem('gv-lang', lang); document.documentElement.lang = lang;
  },
  translations: {
    es: {
      title: 'Gentle-Vanguard Dashboard',
      subtitle: 'Métricas en tiempo real',
      nav: { executive: 'Ejecutivo', operations: 'Operaciones', development: 'Desarrollo', cost: 'Costo', governance: 'Gobernanza', health: 'Salud', live: 'En Vivo', sla: 'SLA', performance: 'Rendimiento', references: 'Referencias', trace: 'Traza', tv: 'TV' },
      sections: { executive: 'Vista Ejecutiva', operations: 'Operaciones', development: 'Desarrollo', cost: 'Costo y ROI', governance: 'Gobernanza', health: 'Salud del Sistema', live: 'Feed en Vivo', sla: 'SLA', performance: 'Rendimiento', references: 'Referencias', trace: 'Trazabilidad en Vivo' },
      cards: { trafficLight: 'Semáforo', tokenStatus: 'Estado Tokens', budgetUsed: 'Presupuesto Usado', estCost: 'Costo Est.', forecast: 'Pronóstico', savings: 'Ahorros', sessions: 'Sesiones', routing: 'Enrutamiento', totalSessions: 'Sesiones Totales', activeNow: 'Activas Ahora', today: 'Hoy', avgDuration: 'Duración Promedio', totalTime: 'Tiempo Total', latest: 'Última', totalCommits: 'Commits Totales', thisMonth: 'Este Mes', thisWeek: 'Esta Semana', prsMerged: 'PRs Mergeados', contributors: 'Contribuidores', linesAdded: 'Líneas Agregadas', linesRemoved: 'Líneas Eliminadas', actualCost: 'Costo Actual', dailyBudget: 'Presupuesto Diario', rate: 'Tarifa', baseline: 'Línea Base', tokensSaved: 'Tokens Ahorrados', roiSignal: 'Señal ROI', tokenGuard: 'Guardia Tokens', routingAcc: 'Precisión Enrutamiento', benchmark: 'Benchmark', status: 'Estado', uptime: 'Disponibilidad', incidents: 'Incidentes', mttr: 'MTTR', latency: 'Latencia', peakActivity: 'Actividad Pico', velocity: 'Velocidad', avgTokensPerSession: 'Tokens Prom./Sesión', baselineWithoutOpt: 'Base sin Opt', topAuthor: 'Top Autor', dataSource: 'Fuente Datos', sessionsPerDay: 'Sesiones/Día', avgSession: 'Sesión Prom.' },
      meta: { executiveStatus: 'estado ejecutivo', budgetGuard: 'guardia presupuesto', tokens: 'tokens', per1M: 'por 1M tokens', projected: 'proyectado', vsBaseline: 'vs línea base', active: 'activas', dispatches: 'despachos', sinceInception: 'desde inicio', currentOpen: 'abiertas actualmente', started: 'iniciadas', perSession: 'por sesión', allTime: 'todo el tiempo', uniqueAuthors: 'autores únicos', last30Commits: 'últimos 30 commits', dayLimit: 'límite diario', withoutOpt: 'sin optimización', reduction: 'reducción', budgetCompliance: 'cumplimiento presupuesto', audited: 'auditados', regressionChecks: 'chequeos regresión', overallGuard: 'guardia general', allSystems: 'todos sistemas operativos', currentlyRunning: 'ejecutándose', passTotal: 'aprobado/total', dispatchAccuracy: 'precisión despacho', localStore: 'almacenamiento local', eventStream: 'flujo eventos', currentUsage: 'uso actual', activeCount: 'conteo activo', highActivity: 'alta actividad', target: 'objetivo', meanRecovery: 'tiempo medio recuperación', last30Days: 'últimos 30 días', average: 'promedio', fromAnalytics: 'de analíticas', commits: 'commits', realData: 'datos reales', duration: 'duración', sessions: 'sesiones', ofTotal: 'de {0} total', reductionPct: '28.6% reducción', usd: 'USD', last30d7d: '30d: {0} - 7d: 0' },
      chartTitles: { tokenTrend: 'Tendencia Tokens', costBreakdown: 'Desglose Costos', sessionActivity: 'Actividad Sesiones', commitsByAuthor: 'Commits por Autor', savingsAnalysis: 'Análisis Ahorros', commitsTimeline: 'Línea Tiempo Commits', inputTokensPerTurn: 'Tokens Entrada por Turno', costPerTurn: 'Costo por Turno (mUSD)' },
      modal: { what: 'Qué', why: 'Por qué', how: 'Cómo', unit: 'Unidad', formula: 'Fórmula' },
      trace: { turns: 'Turnos', input: 'Entrada', output: 'Salida', total: 'Total', cost: 'Costo', ctx: 'Ctx', mechanism: 'Mecanismo:', thinking: 'pensando:', noActiveSession: 'Sin sesión activa', poll: 'Poll:', filterSessions: 'Filtrar sesiones...', loading: 'Cargando...', waitingForTurns: 'Esperando datos de turnos...', loadingMechanisms: 'Cargando mecanismos...', loadingHistory: 'Cargando historial...', filtered: '(filtrado)', turnsSuffix: 'turnos', tk: 'tk', more: '+{0} más', filter: { all: 'Todas', today: 'Hoy', week: 'Semana', month: 'Mes' }, history: { today: 'Hoy', week: 'Esta Semana', month: 'Este Mes', all: 'Todo el Tiempo', rangeDisplay: { day: 'Hoy', week: 'Esta Semana', month: 'Este Mes', all: 'Todo el Tiempo' }, sessions: 'Sesiones', turns: 'Turnos', inTokens: 'Tokens Entrada', outTokens: 'Tokens Salida', total: 'Total', cost: 'Costo', avgPerTurn: 'Prom./Turno', ctxChars: 'Car. Ctx' } },
      refs: { description: 'Esta sección explica el propósito y significado de cada métrica.', purpose: 'Propósito', why: 'Por qué', unit: 'Unidad', formula: 'Fórmula' }
    },
    pt: {
      title: 'Gentle-Vanguard Dashboard',
      subtitle: 'Métricas em tempo real',
      nav: { executive: 'Executivo', operations: 'Operações', development: 'Desenvolvimento', cost: 'Custo', governance: 'Governança', health: 'Saúde', live: 'Ao Vivo', sla: 'SLA', performance: 'Desempenho', references: 'Referências', trace: 'Rastrear', tv: 'TV' },
      sections: { executive: 'Visão Executiva', operations: 'Operações', development: 'Desenvolvimento', cost: 'Custo e ROI', governance: 'Governança', health: 'Saúde do Sistema', live: 'Feed ao Vivo', sla: 'SLA', performance: 'Desempenho', references: 'Referências', trace: 'Rastreabilidade ao Vivo' },
      cards: { trafficLight: 'Semáforo', tokenStatus: 'Status Tokens', budgetUsed: 'Orçamento Usado', estCost: 'Custo Est.', forecast: 'Previsão', savings: 'Economias', sessions: 'Sessões', routing: 'Roteamento', totalSessions: 'Sessões Totais', activeNow: 'Ativas Agora', today: 'Hoje', avgDuration: 'Duração Média', totalTime: 'Tempo Total', latest: 'Última', totalCommits: 'Commits Totais', thisMonth: 'Este Mês', thisWeek: 'Esta Semana', prsMerged: 'PRs Mergeados', contributors: 'Contribuidores', linesAdded: 'Linhas Adicionadas', linesRemoved: 'Linhas Removidas', actualCost: 'Custo Atual', dailyBudget: 'Orçamento Diário', rate: 'Taxa', baseline: 'Linha Base', tokensSaved: 'Tokens Economizados', roiSignal: 'Sinal ROI', tokenGuard: 'Guarda Tokens', routingAcc: 'Precisão Roteamento', benchmark: 'Benchmark', status: 'Status', uptime: 'Disponibilidade', incidents: 'Incidentes', mttr: 'MTTR', latency: 'Latência', peakActivity: 'Atividade Pico', velocity: 'Velocidade', avgTokensPerSession: 'Tokens Méd./Sessão', baselineWithoutOpt: 'Base sem Opt', topAuthor: 'Top Autor', dataSource: 'Fonte Dados', sessionsPerDay: 'Sessões/Dia', avgSession: 'Sessão Méd.' },
      meta: { executiveStatus: 'status executivo', budgetGuard: 'guarda orçamento', tokens: 'tokens', per1M: 'por 1M tokens', projected: 'projetado', vsBaseline: 'vs linha base', active: 'ativas', dispatches: 'despachos', sinceInception: 'desde início', currentOpen: 'abertas atualmente', started: 'iniciadas', perSession: 'por sessão', allTime: 'todo tempo', uniqueAuthors: 'autores únicos', last30Commits: 'últimos 30 commits', dayLimit: 'limite diário', withoutOpt: 'sem otimização', reduction: 'redução', budgetCompliance: 'conformidade orçamentária', audited: 'auditados', regressionChecks: 'checagens regressão', overallGuard: 'guarda geral', allSystems: 'todos sistemas operacionais', currentlyRunning: 'executando', passTotal: 'aprovado/total', dispatchAccuracy: 'precisão despacho', localStore: 'armazenamento local', eventStream: 'fluxo eventos', currentUsage: 'uso atual', activeCount: 'contagem ativa', highActivity: 'alta atividade', target: 'alvo', meanRecovery: 'tempo médio recuperação', last30Days: 'últimos 30 dias', average: 'média', fromAnalytics: 'de analíticas', commits: 'commits', realData: 'dados reais', duration: 'duração', sessions: 'sessões', ofTotal: 'de {0} total', reductionPct: '28.6% redução', usd: 'USD', last30d7d: '30d: {0} - 7d: 0' },
      chartTitles: { tokenTrend: 'Tendência Tokens', costBreakdown: 'Detalhamento Custos', sessionActivity: 'Atividade Sessões', commitsByAuthor: 'Commits por Autor', savingsAnalysis: 'Análise Economias', commitsTimeline: 'Linha Tempo Commits', inputTokensPerTurn: 'Tokens Entrada por Turno', costPerTurn: 'Custo por Turno (mUSD)' },
      modal: { what: 'O quê', why: 'Por quê', how: 'Como', unit: 'Unidade', formula: 'Fórmula' },
      trace: { turns: 'Turnos', input: 'Entrada', output: 'Saída', total: 'Total', cost: 'Custo', ctx: 'Ctx', mechanism: 'Mecanismo:', thinking: 'pensando:', noActiveSession: 'Sem sessão ativa', poll: 'Poll:', filterSessions: 'Filtrar sessões...', loading: 'Carregando...', waitingForTurns: 'Aguardando dados de turnos...', loadingMechanisms: 'Carregando mecanismos...', loadingHistory: 'Carregando histórico...', filtered: '(filtrado)', turnsSuffix: 'turnos', tk: 'tk', more: '+{0} mais', filter: { all: 'Todas', today: 'Hoje', week: 'Semana', month: 'Mês' }, history: { today: 'Hoje', week: 'Esta Semana', month: 'Este Mês', all: 'Todo o Tempo', rangeDisplay: { day: 'Hoje', week: 'Esta Semana', month: 'Este Mês', all: 'Todo o Tempo' }, sessions: 'Sessões', turns: 'Turnos', inTokens: 'Tokens Entrada', outTokens: 'Tokens Saída', total: 'Total', cost: 'Custo', avgPerTurn: 'Méd./Turno', ctxChars: 'Car. Ctx' } },
      refs: { description: 'Esta seção explica o propósito e significado de cada métrica.', purpose: 'Propósito', why: 'Por quê', unit: 'Unidade', formula: 'Fórmula' }
    },
    en: {
      title: 'Gentle-Vanguard Dashboard',
      subtitle: 'Real-time metrics',
      nav: { executive: 'Executive', operations: 'Operations', development: 'Development', cost: 'Cost', governance: 'Governance', health: 'Health', live: 'Live', sla: 'SLA', performance: 'Performance', references: 'Refs', trace: 'Trace', tv: 'TV' },
      sections: { executive: 'Executive Overview', operations: 'Operations', development: 'Development', cost: 'Cost & ROI', governance: 'Governance', health: 'System Health', live: 'Live Feed', sla: 'SLA', performance: 'Performance', references: 'References & Glossary', trace: 'Live Traceability' },
      cards: { trafficLight: 'Traffic Light', tokenStatus: 'Token Status', budgetUsed: 'Budget Used', estCost: 'Est. Cost', forecast: 'Forecast', savings: 'Savings', sessions: 'Sessions', routing: 'Routing', totalSessions: 'Total Sessions', activeNow: 'Active Now', today: 'Today', avgDuration: 'Avg Duration', totalTime: 'Total Time', latest: 'Latest', totalCommits: 'Total Commits', thisMonth: 'This Month', thisWeek: 'This Week', prsMerged: 'PRs Merged', contributors: 'Contributors', linesAdded: 'Lines Added', linesRemoved: 'Lines Removed', actualCost: 'Actual Cost', dailyBudget: 'Daily Budget', rate: 'Rate', baseline: 'Baseline', tokensSaved: 'Tokens Saved', roiSignal: 'ROI Signal', tokenGuard: 'Token Guard', routingAcc: 'Routing Accuracy', benchmark: 'Benchmark', status: 'Status', uptime: 'Uptime', incidents: 'Incidents', mttr: 'MTTR', latency: 'Latency', peakActivity: 'Peak Activity', velocity: 'Velocity', avgTokensPerSession: 'Avg Tokens/Session', baselineWithoutOpt: 'Baseline w/o Opt', topAuthor: 'Top Author', dataSource: 'Data Source', sessionsPerDay: 'Sessions/Day', avgSession: 'Avg Session' },
      meta: { executiveStatus: 'executive status', budgetGuard: 'budget guard', tokens: 'tokens', per1M: 'per 1M tokens', projected: 'projected', vsBaseline: 'vs baseline', active: 'active', dispatches: 'dispatches', sinceInception: 'since inception', currentOpen: 'currently open', started: 'started', perSession: 'per session', allTime: 'all-time', uniqueAuthors: 'unique authors', last30Commits: 'last 30 commits', dayLimit: 'day limit', withoutOpt: 'without optimization', reduction: 'reduction', budgetCompliance: 'budget compliance', audited: 'audited', regressionChecks: 'regression checks', overallGuard: 'overall guard', allSystems: 'all systems operational', currentlyRunning: 'currently running', passTotal: 'pass/total', dispatchAccuracy: 'dispatch accuracy', localStore: 'local store', eventStream: 'event stream', currentUsage: 'current usage', activeCount: 'active count', highActivity: 'high activity', target: 'target', meanRecovery: 'mean time to recovery', last30Days: 'last 30 days', average: 'average', fromAnalytics: 'from analytics', commits: 'commits', realData: 'real data', duration: 'duration', sessions: 'sessions', ofTotal: 'of {0} total', reductionPct: '28.6% reduction', usd: 'USD', last30d7d: '30d: {0} - 7d: 0' },
      chartTitles: { tokenTrend: 'Token Trend', costBreakdown: 'Cost Breakdown', sessionActivity: 'Session Activity', commitsByAuthor: 'Commits by Author', savingsAnalysis: 'Savings Analysis', commitsTimeline: 'Commits Timeline', inputTokensPerTurn: 'Input Tokens per Turn', costPerTurn: 'Cost per Turn (mUSD)' },
      modal: { what: 'What', why: 'Why', how: 'How', unit: 'Unit', formula: 'Formula' },
      trace: { turns: 'Turns', input: 'Input', output: 'Output', total: 'Total', cost: 'Cost', ctx: 'Ctx', mechanism: 'Mechanism:', thinking: 'thinking:', noActiveSession: 'No active session', poll: 'Poll:', filterSessions: 'Filter sessions...', loading: 'Loading...', waitingForTurns: 'Waiting for turn data...', loadingMechanisms: 'Loading mechanisms...', loadingHistory: 'Loading history...', filtered: '(filtered)', turnsSuffix: 'turns', tk: 'tk', more: '+{0} more', filter: { all: 'All', today: 'Today', week: 'Week', month: 'Month' }, history: { today: 'Today', week: 'This Week', month: 'This Month', all: 'All Time', rangeDisplay: { day: 'Today', week: 'This Week', month: 'This Month', all: 'All Time' }, sessions: 'Sessions', turns: 'Turns', inTokens: 'In Tokens', outTokens: 'Out Tokens', total: 'Total', cost: 'Cost', avgPerTurn: 'Avg/Turn', ctxChars: 'Ctx Chars' } },
      refs: { description: 'This section explains the purpose and meaning of each metric.', purpose: 'Purpose', why: 'Why', unit: 'Unit', formula: 'Formula' }
    }
  }
};
