// Metric Information Database
const metricInfo = {
  trafficLight: { what: 'Visual indicator of overall system health status', why: 'Provides executives with immediate understanding of system state', how: 'Aggregated from health checks, error rates, and performance metrics', unit: 'GREEN/YELLOW/RED', formula: 'Based on routing accuracy, error rates, and benchmark results' },
  tokenStatus: { what: 'Budget compliance verification', why: 'Ensures token consumption stays within allocated limits', how: 'Compares current usage against daily limit (120K tokens)', unit: 'PASS or WARNING', formula: 'IF (used/limit < 0.5) THEN PASS ELSE WARNING' },
  budgetUsed: { what: 'Percentage of daily token budget consumed', why: 'Tracks resource utilization and prevents overages', how: 'Calculated from actual token consumption vs daily limit', unit: 'Percentage of 120,000 token daily limit', formula: '(tokens_used / 120000) * 100' },
  estCost: { what: 'Current cost in USD based on token usage', why: 'Real-time financial tracking for budget management', how: 'Calculated using pricing rate of  per 1M tokens', unit: 'USD', formula: '(tokens_used / 1,000,000) * ' },
  forecast: { what: 'Projected month-end cost based on current trend', why: 'Enables proactive budget planning and adjustment', how: 'Linear projection of current daily rate over remaining days', unit: 'USD', formula: 'current_daily_rate * days_in_month' },
  savings: { what: 'Cost savings achieved through optimization', why: 'Measures ROI of efficiency improvements', how: 'Difference between baseline cost and actual cost', unit: 'USD', formula: 'baseline_cost - actual_cost' },
  sessions: { what: 'Total active and historical sessions', why: 'Indicates system usage and adoption', how: 'Count of all sessions in the system', unit: 'Count (integer)', formula: 'SUM(all_sessions)' },
  routing: { what: 'Task routing accuracy percentage', why: 'Measures effectiveness of auto-delegation system', how: 'Percentage of tasks correctly routed to appropriate agents', unit: 'Percentage (target > 95%)', formula: '(correct_routes / total_routes) * 100' },
  totalSessions: { what: 'Cumulative count of all sessions since inception', why: 'Tracks overall system usage over time', how: 'Running total of all created sessions', unit: 'Count (integer)', formula: 'SUM(all_sessions_ever)' },
  activeNow: { what: 'Currently open and active sessions', why: 'Real-time view of current system load', how: 'Count of sessions with status active', unit: 'Count (integer)', formula: 'COUNT(status = active)' },
  today: { what: 'Sessions started today', why: 'Daily activity tracking', how: 'Count of sessions created since midnight', unit: 'Count (integer)', formula: 'COUNT(created_date = today)' },
  avgDuration: { what: 'Average session duration', why: 'Productivity and engagement analysis', how: 'Mean of all session durations', unit: 'Hours', formula: 'SUM(session_durations) / COUNT(sessions)' },
  totalTime: { what: 'Cumulative time across all sessions', why: 'Total resource investment measurement', how: 'Sum of all session durations', unit: 'Minutes', formula: 'SUM(all_session_durations)' },
  latest: { what: 'Most recent active session identifier', why: 'Tracks latest activity', how: 'Session ID with most recent timestamp', unit: 'Session ID string', formula: 'MAX(session.created_at)' },
  totalCommits: { what: 'Total code commits in repository history', why: 'Development activity indicator', how: 'Count from git history', unit: 'Count (integer)', formula: 'git rev-list --all --count' },
  thisMonth: { what: 'Commits made this month', why: 'Monthly development velocity', how: 'Count since first day of current month', unit: 'Count (integer)', formula: 'COUNT(commits_since_month_start)' },
  thisWeek: { what: 'Commits made this week', why: 'Weekly progress tracking', how: 'Count since last Sunday', unit: 'Count (integer)', formula: 'COUNT(commits_since_week_start)' },
  prsMerged: { what: 'Pull requests successfully merged', why: 'Code integration rate metric', how: 'Count of merged PRs vs total created', unit: 'Count (integer)', formula: 'merged_prs / total_prs' },
  contributors: { what: 'Unique developers contributing', why: 'Team size and collaboration metric', how: 'Distinct authors from git log', unit: 'Count (integer)', formula: 'COUNT(DISTINCT authors)' },
  linesAdded: { what: 'Lines of code added', why: 'Development output measurement', how: 'Sum of additions in recent commits', unit: 'Count (integer)', formula: 'SUM(additions)' },
  linesRemoved: { what: 'Lines of code removed', why: 'Code cleanup and refactoring indicator', how: 'Sum of deletions in recent commits', unit: 'Count (integer)', formula: 'SUM(deletions)' },
  actualCost: { what: 'Current spending based on usage', why: 'Real-time cost monitoring', how: 'Calculated from token consumption', unit: 'USD', formula: '(tokens_used / 1,000,000) * ' },
  dailyBudget: { what: 'Maximum tokens allowed per day', why: 'Spending limit and budget control', how: 'Configured limit (120,000 tokens)', unit: 'Tokens', formula: 'Fixed: 120,000' },
  rate: { what: 'Cost per million tokens', why: 'Pricing reference and cost estimation', how: 'Current API pricing rate', unit: 'USD per 1M tokens', formula: 'Fixed: /1M tokens' },
  baseline: { what: 'Estimated tokens without optimization', why: 'Efficiency comparison baseline', how: 'Historical average before optimizations', unit: 'Tokens', formula: 'Historical average * current_period' },
  tokensSaved: { what: 'Tokens saved through optimization', why: 'Efficiency measurement', how: 'Difference between baseline and actual', unit: 'Tokens', formula: 'baseline - actual' },
  roiSignal: { what: 'Return on investment indicator', why: 'Executive-level ROI assessment', how: 'Derived from health status and savings', unit: 'GREEN/YELLOW/RED', formula: 'Based on savings percentage and health' },
  tokenGuard: { what: 'Budget compliance check', why: 'Financial governance control', how: 'Validates spending within limits', unit: 'PASS/FAIL', formula: 'IF cost < budget THEN PASS ELSE FAIL' },
  routingAcc: { what: 'Task routing accuracy from audit', why: 'System reliability metric', how: 'Audited from dispatch logs', unit: 'Percentage', formula: '(correct / total) * 100' },
  benchmark: { what: 'Performance benchmark results', why: 'Quality assurance metric', how: 'Automated regression tests', unit: 'Pass/Total', formula: 'passed_tests / total_tests' },
  status: { what: 'Overall system health status', why: 'Operational state indicator', how: 'Aggregated health checks', unit: 'HEALTHY/DEGRADED/DOWN', formula: 'Based on component health' },
  uptime: { what: 'System availability percentage', why: 'Reliability commitment metric', how: 'Time system was available / total time', unit: 'Percentage (target 99.9%)', formula: '(available_time / total_time) * 100' },
  incidents: { what: 'Service disruption count', why: 'Problem tracking', how: 'Logged incidents over period', unit: 'Count (integer)', formula: 'COUNT(incidents)' },
  mttr: { what: 'Mean Time To Recovery', why: 'Recovery speed measurement', how: 'Average time to resolve incidents', unit: 'Minutes', formula: 'SUM(recovery_times) / COUNT(incidents)' },
  latency: { what: 'Response time', why: 'Performance metric', how: 'Time from request to response', unit: 'Seconds', formula: 'response_time - request_time' },
  peakActivity: { what: 'Hour with most activity', why: 'Capacity planning', how: 'Hour with maximum session count', unit: 'HH:MM', formula: 'MAX(sessions_by_hour)' },
  velocity: { what: 'Development velocity change', why: 'Team productivity trend', how: 'Percentage change in commits', unit: 'Percentage', formula: '((current - previous) / previous) * 100' },
  liveStatus: { what: 'Real-time event stream status', why: 'Indicates live data connection', how: 'WebSocket or polling connection state', unit: 'LIVE/DISCONNECTED', formula: 'Connection state' },
  peakActivityFlag: { what: 'High activity period indicator', why: 'Identifies peak usage times', how: 'Checks if current hour is 17:00-20:00', unit: 'YES/NO', formula: 'IF hour IN [17,18,19,20] THEN YES' }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { metricInfo };
}
