import { createContext, useContext, useState, type ReactNode } from 'react';

export type Locale = 'en' | 'es' | 'pt-BR';

export const LOCALE_NAMES: Record<Locale, string> = {
  en: 'English',
  es: 'Español',
  'pt-BR': 'Português (Brasil)',
};

export const LOCALE_FLAGS: Record<Locale, string> = {
  en: '🇬🇧',
  es: '🇪🇸',
  'pt-BR': '🇧🇷',
};

const STRINGS: Record<Locale, Record<string, string>> = {
  en: {
    // Brand / nav
    'brand.analytics': 'Analytics',
    'nav.sections': 'Sections',
    'nav.connection': 'Connection',
    'nav.analysis': 'Analysis',
    'nav.report': 'Report',
    'nav.evidence': 'Evidence',
    'state.ready': 'Atlassian ready',
    'state.partial': 'Partial connection',
    'state.none': 'No connection',
    'theme.toLight': 'Switch to light theme',
    'theme.toDark': 'Switch to dark theme',
    'theme.toggle': 'Toggle theme',

    // Connection panel
    'conn.title': 'Atlassian Connection',
    'conn.loaded': 'Credentials loaded for this local run.',
    'conn.configure': 'Configure the connection once to operate.',
    'conn.site': 'Site',
    'conn.bitbucket': 'Bitbucket',
    'conn.workspaceUndefined': 'Workspace not set',
    'conn.revalidate': 'Revalidate',
    'conn.edit': 'Edit',
    'conn.siteUrl': 'Site URL',
    'conn.email': 'Email',
    'conn.apiToken': 'API token',
    'conn.bitbucketWorkspace': 'Bitbucket workspace',
    'conn.test': 'Test',
    'conn.saveAndTest': 'Save and test',
    'conn.oauthOpened': 'Atlassian opened in a new tab. Authorize the app and come back.',
    'conn.saved': 'Connection saved and verified.',
    'conn.validAll': 'Connection valid for all 3 services.',
    'conn.partial': 'Partial connection, check the per-service detail.',
    'conn.oauthRemoved': 'OAuth tokens removed from the vault.',

    // Status panel
    'status.title': 'Status',
    'status.operational': 'Session operational without exposing credentials.',
    'status.pending': 'Pending connection.',
    'status.pendingShort': 'Pending',

    // History
    'history.title': 'History',
    'history.subtitle': 'Last 5 reports persisted in Nexus, ready to resume.',
    'history.empty': 'No reports yet.',

    // Analysis
    'analysis.mode': 'Analysis mode',
    'analysis.url': 'URL',
    'analysis.request': 'Request',
    'analysis.export': 'Export',
    'analysis.template': 'Template',
    'analysis.urlPlaceholder': 'Paste a Jira, Confluence, Bitbucket, PR or repository URL...',
    'analysis.requestPlaceholder':
      'Paste the functional or technical request to analyze impact, fronts, roles and estimate...',
    'analysis.run': 'Analyze',

    // Report
    'report.emptyTitle': 'Ready to interpret an initiative',
    'report.emptyBody':
      'The first analysis will retrieve evidence, detect impact fronts and produce a technical response ready to evolve.',
    'report.label': 'Report',
    'report.complexity': 'Complexity',
    'report.delivery': 'Delivery',
    'report.qa': 'QA',
    'report.confidence': 'Confidence',
    'report.currentState': 'Current state',
    'report.proposedSolution': 'Proposed solution',
    'report.fronts': 'Fronts involved',
    'report.roles': 'Roles',
    'report.qaScenarios': 'QA scenarios',
    'report.nextActions': 'Next actions',
    'report.evidence': 'Evidence',
    'report.proposedState': 'Proposed state',
    'report.noContent': 'No content.',
    'report.copy': 'Copy',
    'report.copied': 'Copied',
    'report.mermaidRender': 'render mermaid:',

    // OAuth
    'oauth.title': 'OAuth 2.0 (3LO)',
    'oauth.connected': 'Connected',
    'oauth.ready': 'Ready to authorize',
    'oauth.notConfigured': 'Not configured',
    'oauth.expires': 'Expires:',
    'oauth.disconnect': 'Disconnect',
    'oauth.callback': 'Local callback:',
    'oauth.scopes': 'Scopes:',
    'oauth.configureHint':
      'Set GVA_OAUTH_CLIENT_ID and GVA_OAUTH_CLIENT_SECRET in the server environment to enable OAuth.',
    'oauth.connect': 'Connect with Atlassian',

    // LLM provenance
    'llm.agent': 'Generated by LLM (sdd-explore)',
    'llm.cache': 'Retrieved from LLM cache',
    'llm.fallback': 'Heuristic fallback (LLM unavailable)',
    'llm.heuristic': 'Local heuristic',
  },
  es: {
    'brand.analytics': 'Analytics',
    'nav.sections': 'Secciones',
    'nav.connection': 'Conexión',
    'nav.analysis': 'Análisis',
    'nav.report': 'Reporte',
    'nav.evidence': 'Evidencia',
    'state.ready': 'Atlassian listo',
    'state.partial': 'Conexión parcial',
    'state.none': 'Sin conexión',
    'theme.toLight': 'Cambiar a tema claro',
    'theme.toDark': 'Cambiar a tema oscuro',
    'theme.toggle': 'Cambiar tema',

    'conn.title': 'Conexión Atlassian',
    'conn.loaded': 'Credenciales cargadas para esta ejecución local.',
    'conn.configure': 'Configura la conexión una sola vez para operar.',
    'conn.site': 'Site',
    'conn.bitbucket': 'Bitbucket',
    'conn.workspaceUndefined': 'Workspace no definido',
    'conn.revalidate': 'Revalidar',
    'conn.edit': 'Editar',
    'conn.siteUrl': 'Site URL',
    'conn.email': 'Email',
    'conn.apiToken': 'API token',
    'conn.bitbucketWorkspace': 'Bitbucket workspace',
    'conn.test': 'Probar',
    'conn.saveAndTest': 'Guardar y probar',
    'conn.oauthOpened': 'Atlassian abierto en nueva pestaña. Autoriza la app y vuelve acá.',
    'conn.saved': 'Conexión guardada y verificada.',
    'conn.validAll': 'Conexión válida para los 3 servicios.',
    'conn.partial': 'Conexión parcial, revisa el detalle por servicio.',
    'conn.oauthRemoved': 'Tokens OAuth eliminados del vault.',

    'status.title': 'Estado',
    'status.operational': 'Sesión operativa sin exponer credenciales.',
    'status.pending': 'Pendiente de conexión.',
    'status.pendingShort': 'Pendiente',

    'history.title': 'Historial',
    'history.subtitle': 'Últimos 5 reportes persistidos en Nexus, listos para retomar.',
    'history.empty': 'Sin reportes todavía.',

    'analysis.mode': 'Modo de análisis',
    'analysis.url': 'URL',
    'analysis.request': 'Pedido',
    'analysis.export': 'Exportar',
    'analysis.template': 'Plantilla',
    'analysis.urlPlaceholder': 'Pega una URL de Jira, Confluence, Bitbucket, PR o repositorio...',
    'analysis.requestPlaceholder':
      'Pega el pedido funcional o técnico para analizar impacto, frentes, roles y estimación...',
    'analysis.run': 'Analizar',

    'report.emptyTitle': 'Listo para interpretar una iniciativa',
    'report.emptyBody':
      'El primer análisis va a recuperar evidencia, detectar frentes de impacto y producir una respuesta técnica lista para evolucionar.',
    'report.label': 'Reporte',
    'report.complexity': 'Complejidad',
    'report.delivery': 'Delivery',
    'report.qa': 'QA',
    'report.confidence': 'Confianza',
    'report.currentState': 'Estado actual',
    'report.proposedSolution': 'Solución propuesta',
    'report.fronts': 'Frentes involucrados',
    'report.roles': 'Roles',
    'report.qaScenarios': 'Escenarios QA',
    'report.nextActions': 'Próximas acciones',
    'report.evidence': 'Evidencia',
    'report.proposedState': 'Estado propuesto',
    'report.noContent': 'Sin contenido.',
    'report.copy': 'Copiar',
    'report.copied': 'Copiado',
    'report.mermaidRender': 'render mermaid:',

    'oauth.title': 'OAuth 2.0 (3LO)',
    'oauth.connected': 'Conectado',
    'oauth.ready': 'Listo para autorizar',
    'oauth.notConfigured': 'No configurado',
    'oauth.expires': 'Expira:',
    'oauth.disconnect': 'Desconectar',
    'oauth.callback': 'Callback local:',
    'oauth.scopes': 'Scopes:',
    'oauth.configureHint':
      'Configurar GVA_OAUTH_CLIENT_ID y GVA_OAUTH_CLIENT_SECRET en el entorno del server para habilitar OAuth.',
    'oauth.connect': 'Conectar con Atlassian',

    'llm.agent': 'Generado por LLM (sdd-explore)',
    'llm.cache': 'Recuperado del cache LLM',
    'llm.fallback': 'Fallback heurístico (LLM no disponible)',
    'llm.heuristic': 'Heurístico local',
  },
  'pt-BR': {
    'brand.analytics': 'Analytics',
    'nav.sections': 'Seções',
    'nav.connection': 'Conexão',
    'nav.analysis': 'Análise',
    'nav.report': 'Relatório',
    'nav.evidence': 'Evidência',
    'state.ready': 'Atlassian pronto',
    'state.partial': 'Conexão parcial',
    'state.none': 'Sem conexão',
    'theme.toLight': 'Mudar para tema claro',
    'theme.toDark': 'Mudar para tema escuro',
    'theme.toggle': 'Alternar tema',

    'conn.title': 'Conexão Atlassian',
    'conn.loaded': 'Credenciais carregadas para esta execução local.',
    'conn.configure': 'Configure a conexão uma vez para operar.',
    'conn.site': 'Site',
    'conn.bitbucket': 'Bitbucket',
    'conn.workspaceUndefined': 'Workspace não definido',
    'conn.revalidate': 'Revalidar',
    'conn.edit': 'Editar',
    'conn.siteUrl': 'Site URL',
    'conn.email': 'Email',
    'conn.apiToken': 'API token',
    'conn.bitbucketWorkspace': 'Bitbucket workspace',
    'conn.test': 'Testar',
    'conn.saveAndTest': 'Salvar e testar',
    'conn.oauthOpened': 'Atlassian aberto em nova aba. Autorize o app e volte aqui.',
    'conn.saved': 'Conexão salva e verificada.',
    'conn.validAll': 'Conexão válida para os 3 serviços.',
    'conn.partial': 'Conexão parcial, revise o detalhe por serviço.',
    'conn.oauthRemoved': 'Tokens OAuth removidos do vault.',

    'status.title': 'Status',
    'status.operational': 'Sessão operacional sem expor credenciais.',
    'status.pending': 'Pendente de conexão.',
    'status.pendingShort': 'Pendente',

    'history.title': 'Histórico',
    'history.subtitle': 'Últimos 5 relatórios persistidos no Nexus, prontos para retomar.',
    'history.empty': 'Sem relatórios ainda.',

    'analysis.mode': 'Modo de análise',
    'analysis.url': 'URL',
    'analysis.request': 'Pedido',
    'analysis.export': 'Exportar',
    'analysis.template': 'Modelo',
    'analysis.urlPlaceholder': 'Cole uma URL de Jira, Confluence, Bitbucket, PR ou repositório...',
    'analysis.requestPlaceholder':
      'Cole o pedido funcional ou técnico para analisar impacto, frentes, papéis e estimativa...',
    'analysis.run': 'Analisar',

    'report.emptyTitle': 'Pronto para interpretar uma iniciativa',
    'report.emptyBody':
      'A primeira análise vai recuperar evidências, detectar frentes de impacto e produzir uma resposta técnica pronta para evoluir.',
    'report.label': 'Relatório',
    'report.complexity': 'Complexidade',
    'report.delivery': 'Delivery',
    'report.qa': 'QA',
    'report.confidence': 'Confiança',
    'report.currentState': 'Estado atual',
    'report.proposedSolution': 'Solução proposta',
    'report.fronts': 'Frentes envolvidas',
    'report.roles': 'Papéis',
    'report.qaScenarios': 'Cenários QA',
    'report.nextActions': 'Próximas ações',
    'report.evidence': 'Evidência',
    'report.proposedState': 'Estado proposto',
    'report.noContent': 'Sem conteúdo.',
    'report.copy': 'Copiar',
    'report.copied': 'Copiado',
    'report.mermaidRender': 'render mermaid:',

    'oauth.title': 'OAuth 2.0 (3LO)',
    'oauth.connected': 'Conectado',
    'oauth.ready': 'Pronto para autorizar',
    'oauth.notConfigured': 'Não configurado',
    'oauth.expires': 'Expira:',
    'oauth.disconnect': 'Desconectar',
    'oauth.callback': 'Callback local:',
    'oauth.scopes': 'Scopes:',
    'oauth.configureHint':
      'Defina GVA_OAUTH_CLIENT_ID e GVA_OAUTH_CLIENT_SECRET no ambiente do servidor para habilitar OAuth.',
    'oauth.connect': 'Conectar com Atlassian',

    'llm.agent': 'Gerado por LLM (sdd-explore)',
    'llm.cache': 'Recuperado do cache LLM',
    'llm.fallback': 'Fallback heurístico (LLM indisponível)',
    'llm.heuristic': 'Heurístico local',
  },
};

const LocaleContext = createContext<{ locale: Locale; setLocale: (l: Locale) => void }>({
  locale: 'es',
  setLocale: () => {},
});

export function LocaleProvider({ children }: { children: ReactNode }) {
  const [locale, setLocale] = useState<Locale>(() => {
    if (typeof window === 'undefined') return 'es';
    const stored = window.localStorage.getItem('gv-analytics-locale');
    return stored === 'en' || stored === 'pt-BR' || stored === 'es' ? stored : 'es';
  });
  return <LocaleContext.Provider value={{ locale, setLocale }}>{children}</LocaleContext.Provider>;
}

export function useLocale() {
  return useContext(LocaleContext);
}

export function useT(): { tt: (key: string) => string } {
  const { locale } = useLocale();
  const tt = (key: string): string => STRINGS[locale][key] ?? STRINGS.en[key] ?? key;
  return { tt };
}

export function LocaleSwitcher() {
  const { locale, setLocale } = useLocale();
  return (
    <select
      className="locale-switcher"
      value={locale}
      onChange={(event) => setLocale(event.target.value as Locale)}
      aria-label="Language / Idioma / Idioma"
      title="Language"
    >
      {(Object.keys(LOCALE_NAMES) as Locale[]).map((l) => (
        <option key={l} value={l}>
          {LOCALE_FLAGS[l]} {LOCALE_NAMES[l]}
        </option>
      ))}
    </select>
  );
}
