<#
.SYNOPSIS
    Autonomous Norm Enforcer - Validates and applies learned norms
    
.DESCRIPTION
    Runs at session start/close or on orchestrator demand.
    Validates directory structure, documentation placement, and norms.
    Creates missing directories and applies corrections automatically.
    
.PARAMETER Trigger
    What triggered this run: session-start, session-close, orchestrator, manual
    
.PARAMETER AutoFix
    Apply fixes automatically (default: true for autonomous operation)
    
.PARAMETER Verbose
    Show detailed output
    
.EXAMPLE
    .\auto-norm-enforcer.ps1 -Trigger session-start -AutoFix
    
.NOTES
    Author: foundation
    Version: 1.0.0
#>

param(
    [Parameter(Mandatory=$false)]
    [ValidateSet("session-start", "session-close", "orchestrator", "manual")]
    [string]$Trigger = "manual",
    
    [Parameter(Mandatory=$false)]
    [switch]$AutoFix = $true,
    
    [Parameter(Mandatory=$false)]
    [switch]$VerboseOutput
)

$ErrorActionPreference = 'Stop'
$repoRoot = if ($env:FOUNDATION_BASE_DIR -and (Test-Path $env:FOUNDATION_BASE_DIR)) { $env:FOUNDATION_BASE_DIR } else {
    $root = Split-Path -Parent $PSScriptRoot
    while ($root -and -not (Test-Path (Join-Path $root 'config'))) { $root = Split-Path -Parent $root }
    if (-not $root) { $root = $PSScriptRoot }
    $root
}

# Load learned norms
$adaptiveRulesPath = Join-Path $repoRoot "rules\adaptive"
$learnedNormsPath = Join-Path $adaptiveRulesPath "LEARNED-NORMS.md"

$script:Issues = @()
$script:Fixes = @()
$script:NormsApplied = @()

function Write-Norm {
    param([string]$Message)
    if ($VerboseOutput) {
        Write-Host "[NORM-ENFORCER] $Message" -ForegroundColor Cyan
    }
}

function Write-NormFix {
    param([string]$Message)
    Write-Host "[NORM-FIX] $Message" -ForegroundColor Green
}

function Write-NormWarn {
    param([string]$Message)
    Write-Host "[NORM-WARN] $Message" -ForegroundColor Yellow
}

# Load learned norms from Engram memory and adaptive rules
function Get-LearnedNorms {
    $norms = @()
    
    # 1. Load from LEARNED-NORMS.md
    if (Test-Path $learnedNormsPath) {
        $content = Get-Content $learnedNormsPath -Raw
        # Extract norms from markdown table (simplified parser)
        if ($content -match '### Documentation Placement([\s\S]*?)###') {
            $section = $matches[1]
            foreach ($line in ($section -split "`n")) {
                if ($line -match '\| (\w+-\d+) \| (.+?) \| (\w+) \| (.+?) \|') {
                    $norms += [PSCustomObject]@{
                        ID = $matches[1]
                        Norm = $matches[2].Trim()
                        Confidence = $matches[3].Trim()
                        Source = $matches[4].Trim()
                    }
                }
            }
        }
    }
    
    # 2. Load from Engram memory (simulated - would call engram_mem_search)
    # In real implementation, this would query Engram for documentation patterns
    
    return $norms
}

# Validate docs directory structure
function Test-DocsStructure {
    Write-Norm "Validating docs directory structure..."
    
    $docsPath = Join-Path $repoRoot "docs"
    if (-not (Test-Path $docsPath)) {
        $script:Issues += "Missing docs/ directory"
        if ($AutoFix) {
            New-Item -Path $docsPath -ItemType Directory -Force | Out-Null
            $script:Fixes += "Created docs/"
            Write-NormFix "Created docs/ directory"
        }
    }
    
    # Check for required subdirectories based on learned norms
    $requiredDirs = @("getting-started", "guides", "reference", "supplementary", "sessions")
    
    foreach ($dir in $requiredDirs) {
        $dirPath = Join-Path $docsPath $dir
        if (-not (Test-Path $dirPath)) {
            $script:Issues += "Missing docs/$dir/"
            if ($AutoFix) {
                New-Item -Path $dirPath -ItemType Directory -Force | Out-Null
                $script:Fixes += "Created docs/$dir/"
                Write-NormFix "Created docs/$dir/"
            }
        }
    }
    
    # Ensure docs/README.md exists (master index)
    $docsReadme = Join-Path $docsPath "README.md"
    if (-not (Test-Path $docsReadme)) {
        $script:Issues += "Missing docs/README.md (master index)"
        if ($AutoFix) {
            $content = @"
# Documentation Index

## Quick Navigation

- [Getting Started](getting-started/) - Setup guides
- [Guides](guides/) - How-to and strategies
- [Reference](reference/) - Technical specs
- [Supplementary](supplementary/) - Resources
- [Sessions](sessions/) - Session notes

## Role-Based Navigation

### For New Developers
1. Start with [getting-started/](getting-started/)
2. Review [reference/](reference/) for technical details

### For Architects
1. Check [guides/](guides/) for design decisions
2. Review [sessions/](sessions/) for past decisions

---
Auto-generated by norm-enforcer at $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
"@
            Set-Content -Path $docsReadme -Value $content -Encoding UTF8
            $script:Fixes += "Created docs/README.md"
            Write-NormFix "Created docs/README.md"
        }
    }
}

# Validate documentation standards
function Test-DocumentationStandards {
    Write-Norm "Validating documentation standards..."
    
    $norms = Get-LearnedNorms
    
    # Apply DOC-003: English-first
    $docsPath = Join-Path $repoRoot "docs"
    if (Test-Path $docsPath) {
        Get-ChildItem -Path $docsPath -Filter "*.md" -Recurse -File | ForEach-Object {
            $content = Get-Content $_.FullName -Raw -Encoding UTF8 -ErrorAction SilentlyContinue
            if ($content) {
                # Quick check: if >50% of content is non-ASCII, warn
                $nonAscii = ($content.ToCharArray() | Where-Object { $_.Value -gt 127 }).Count
                $total = $content.Length
                if ($total -gt 0 -and ($nonAscii / $total) -gt 0.5) {
                    $script:Issues += "File may not be English-first: $($_.FullName.Substring($repoRoot.Length+1))"
                }
            }
        }
    }
}

# Main execution
function Invoke-NormEnforcement {
    Write-Host "" -ForegroundColor Green
    Write-Host "[SEARCH] NORM ENFORCER (Trigger: $Trigger)" -ForegroundColor Green
    Write-Host "" -ForegroundColor Green
    Write-Host ""
    
    Test-DocsStructure
    Test-DocumentationStandards
    
    # Summary
    Write-Host ""
    Write-Host "" -ForegroundColor Cyan
    Write-Host "[DATA] SUMMARY" -ForegroundColor Cyan
    Write-Host "" -ForegroundColor Cyan
    Write-Host "  Issues found: $($script:Issues.Count)" -ForegroundColor Yellow
    Write-Host "  Fixes applied: $($script:Fixes.Count)" -ForegroundColor Green
    Write-Host ""
    
    if ($script:Issues.Count -gt 0 -and -not $AutoFix) {
        Write-Host "  Issues found (run with -AutoFix to correct):" -ForegroundColor Yellow
        $script:Issues | ForEach-Object { Write-Host "   - $_" -ForegroundColor Gray }
    }
    
    if ($script:Fixes.Count -gt 0) {
        Write-Host " Fixes applied:" -ForegroundColor Green
        $script:Fixes | ForEach-Object { Write-Host "   - $_" -ForegroundColor Gray }
    }
    
    # Return status for orchestrator
    $result = @{
        Trigger = $Trigger
        Issues = $script:Issues
        Fixes = $script:Fixes
        Status = if ($script:Issues.Count -eq 0 -or $script:Fixes.Count -gt 0) { "PASS" } else { "NEEDS_FIX" }
        Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    }
    
    return $result
}

# Execute
Invoke-NormEnforcement



