<#
.SYNOPSIS
    Autonomous Norm Enforcer - Validates and applies learned norms
    
.DESCRIPTION
    Runs at session start/close or on orchestrator demand.
    Validates directory structure, documentation placement, and norms.
    Creates missing directories and applies corrections automatically.
    
.PARAMETER Trigger
    What triggered this run: session-start, session-close, orchestrator, manual
    
.PARAMETER AutoFix
    Apply fixes automatically (default: true for autonomous operation)
    
.PARAMETER Verbose
    Show detailed output
    
.EXAMPLE
    .\auto-norm-enforcer.ps1 -Trigger session-start -AutoFix
    
.NOTES
    Author: gentle-vanguard
    Version: 1.0.0
#>

param(
    [Parameter(Mandatory=$false)]
    [ValidateSet("session-start", "session-close", "orchestrator", "manual")]
    [string]$Trigger = "manual",
    
    [Parameter(Mandatory=$false)]
    [switch]$AutoFix = $true,
    
    [Parameter(Mandatory=$false)]
    [switch]$VerboseOutput
)

$ErrorActionPreference = 'Continue'
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$loggerModule = Join-Path $scriptDir '..\common\Logger.psm1'
if (Test-Path $loggerModule) { Import-Module $loggerModule -Force }
$repoRoot = if ($env:GENTLE_VANGUARD_BASE_DIR -and (Test-Path $env:GENTLE_VANGUARD_BASE_DIR)) { $env:GENTLE_VANGUARD_BASE_DIR } else {
    $root = Split-Path -Parent $PSScriptRoot
    while ($root -and -not (Test-Path (Join-Path $root 'config\orchestrator.json'))) { $root = Split-Path -Parent $root }
    if (-not $root) { $root = $PSScriptRoot }
    $root
}

# Load learned norms
$adaptiveRulesPath = Join-Path $repoRoot "rules\adaptive"
$learnedNormsPath = Join-Path $adaptiveRulesPath "LEARNED-NORMS.md"

$script:Issues = @()
$script:Fixes = @()
$script:NormsApplied = @()

function Write-Norm {
    param([string]$Message)
    if ($VerboseOutput) {
        Write-Host "[NORM-ENFORCER] $Message" -ForegroundColor Cyan
    }
    try { Write-Log -Level DEBUG -Message $Message -Component 'norm-enforcer' } catch {}
}

function Write-NormFix {
    param([string]$Message)
    Write-Host "[NORM-FIX] $Message" -ForegroundColor Green
}

function Write-NormWarn {
    param([string]$Message)
    Write-Host "[NORM-WARN] $Message" -ForegroundColor Yellow
}

# Load learned norms from Engram memory and adaptive rules
function Get-LearnedNorms {
    $norms = @()
    
    if (Test-Path $learnedNormsPath) {
        $content = Get-Content $learnedNormsPath -Raw
        $regex = [regex]::new('\| (\w+-\d+) \| (.+?) \| (\w+) \| (.+?) \| (\d{4}-\d{2}-\d{2}) \|')
        $matches = $regex.Matches($content)
        foreach ($m in $matches) {
            $norms += [PSCustomObject]@{
                ID = $m.Groups[1].Value
                Norm = $m.Groups[2].Value.Trim()
                Confidence = $m.Groups[3].Value.Trim()
                Source = $m.Groups[4].Value.Trim()
                Date = $m.Groups[5].Value.Trim()
            }
        }
        Write-Norm "Loaded $($norms.Count) norms from LEARNED-NORMS.md"
    }
    
    return $norms
}

# Validate docs directory structure
function Test-DocsStructure {
    Write-Norm "Validating docs directory structure..."
    
    $docsPath = Join-Path $repoRoot "docs"
    if (-not (Test-Path $docsPath)) {
        $script:Issues += "Missing docs/ directory"
        if ($AutoFix) {
            New-Item -Path $docsPath -ItemType Directory -Force | Out-Null
            $script:Fixes += "Created docs/"
            Write-NormFix "Created docs/ directory"
        }
    }
    
    # Check for required subdirectories based on learned norms
    $requiredDirs = @("getting-started", "guides", "reference", "supplementary", "sessions")
    
    foreach ($dir in $requiredDirs) {
        $dirPath = Join-Path $docsPath $dir
        if (-not (Test-Path $dirPath)) {
            $script:Issues += "Missing docs/$dir/"
            if ($AutoFix) {
                New-Item -Path $dirPath -ItemType Directory -Force | Out-Null
                $script:Fixes += "Created docs/$dir/"
                Write-NormFix "Created docs/$dir/"
            }
        }
    }
    
    # Ensure docs/README.md exists (master index)
    $docsReadme = Join-Path $docsPath "README.md"
    if (-not (Test-Path $docsReadme)) {
        $script:Issues += "Missing docs/README.md (master index)"
        if ($AutoFix) {
            $content = @"
# Documentation Index

## Quick Navigation

- [Getting Started](getting-started/) - Setup guides
- [Guides](guides/) - How-to and strategies
- [Reference](reference/) - Technical specs
- [Supplementary](supplementary/) - Resources
- [Sessions](sessions/) - Session notes

## Role-Based Navigation

### For New Developers
1. Start with [getting-started/](getting-started/)
2. Review [reference/](reference/) for technical details

### For Architects
1. Check [guides/](guides/) for design decisions
2. Review [sessions/](sessions/) for past decisions

---
Auto-generated by norm-enforcer at $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
"@
            Set-Content -Path $docsReadme -Value $content -Encoding UTF8
            $script:Fixes += "Created docs/README.md"
            Write-NormFix "Created docs/README.md"
        }
    }
}

# Validate documentation standards
function Test-DocumentationStandards {
    Write-Norm "Validating documentation standards..."
    
    $norms = Get-LearnedNorms
    
    # Apply DOC-003: English-first
    $docsPath = Join-Path $repoRoot "docs"
    if (Test-Path $docsPath) {
        Get-ChildItem -Path $docsPath -Filter "*.md" -Recurse -File | ForEach-Object {
            $content = Get-Content $_.FullName -Raw -Encoding UTF8 -ErrorAction SilentlyContinue
            if ($content) {
                # Quick check: if >50% of content is non-ASCII, warn
                $nonAscii = ($content.ToCharArray() | Where-Object { $_.Value -gt 127 }).Count
                $total = $content.Length
                if ($total -gt 0 -and ($nonAscii / $total) -gt 0.5) {
                    $script:Issues += "File may not be English-first: $($_.FullName.Substring($repoRoot.Length+1))"
                }
            }
        }
    }
}

# Main execution
function Invoke-NormEnforcement {
    Write-Host "[NORM-ENFORCER] Trigger: $Trigger" -ForegroundColor Green
    Write-Log -Level INFO -Message "Iniciando validación de normas" -Component 'norm-enforcer' -Data @{trigger=$Trigger;autoFix=$AutoFix.IsPresent}
    
    Test-DocsStructure
    Test-DocumentationStandards
    
    Write-Host "[NORM-ENFORCER] Issues: $($script:Issues.Count), Fixes: $($script:Fixes.Count)" -ForegroundColor Cyan
    Write-Log -Level INFO -Message "Validación completada: $($script:Fixes.Count) fixes, $($script:Issues.Count) issues" -Component 'norm-enforcer' -Data @{issuesCount=$script:Issues.Count;fixesCount=$script:Fixes.Count;normsApplied=$script:NormsApplied.Count}
    
    if ($script:Issues.Count -gt 0 -and -not $AutoFix) {
        $script:Issues | ForEach-Object { Write-Host "   - $_" -ForegroundColor Yellow }
    }
    
    if ($script:Fixes.Count -gt 0) {
        $script:Fixes | ForEach-Object { Write-Host "   - $_" -ForegroundColor Green }
    }
    
    $result = @{
        Trigger = $Trigger
        Issues = $script:Issues
        Fixes = $script:Fixes
        Status = if ($script:Issues.Count -eq 0 -or $script:Fixes.Count -gt 0) { "PASS" } else { "NEEDS_FIX" }
        Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    }
    
    return $result
}

Invoke-NormEnforcement
