flowchart LR
  classDef default fill:#1a2035,stroke:#00bfff,color:#e0e0e0
  classDef func fill:#1a2035,stroke:#00ff88,color:#e0e0e0
  classDef method fill:#1a2035,stroke:#ffaa00,color:#e0e0e0

  c40[buildSystemPrompt]
  c23[cmdAdd]
  c89[tick]
  c94[getPluginTools]
  c44[stop]
  c104[ensureDir]
  c47[add]
  c85[nltimeparserjs]
  c15[render]
  c30[maingo]
  c0[grindts]
  c92[truncate]
  c103[checkOutbound]
  c79[handleScheduleCommand]
  c22[defaultDataPath]
  c37[time]
  c45[save]
  c76[pluginloaderjs]
  c32[errors]
  c61[contextjs]
  c14[buildDots]
  c56[agentjs]
  c52[executeTool]
  c6[generateMissionYaml]
  c88[executeTask]
  c13[generateWindsurfConfig]
  c7[adapterjs]
  c46[processMessage]
  c72[scanPlugins]
  c73[getPluginDir]
  c17[pad]
  c5[generateAGENTSmd]
  c74[getPluginExecutor]
  c49[runReAct]
  c101[nodecrypto]
  c98[getFeedbackTrend]
  c4[mapSkillToAgentRole]
  c42[load]
  c67[getSchedulesCount]
  c87[parseCron]
  c38[constructor]
  c21[printHelp]
  c8[convertSkillToCodex]
  c1[fs]
  c51[callLLM]
  c77[sched]
  c48[handleIncomingMessage]
  c64[sort]
  c39[getProjectContext]
  c16[updateChrome]
  c75[reloadPlugins]
  c34[fmt]
  c82[removeTask]
  c36[pathfilepath]
  c20[main]
  c90[cronMatches]
  c93[buildToolDefs]
  c68[getPlatformsActive]
  c24[cmdList]
  c95[listSupportedPatterns]
  c80[formatScheduleList]
  c50[get]
  c53[callOpenAI]
  c27[loadStore]
  c33[flag]
  c66[countJson]
  c78[getScheduler]
  c2[convertSkillToAntigravity]
  c65[isRunning]
  c83[addTask]
  c54[callAnthropic]
  c70[parseNLToCron]
  c86[schedulerjs]
  c9[generateToolsArray]
  c10[generateProxyServer]
  c63[getLastProcessedAt]
  c59[toolsjs]
  c99[pluginloaderjs]
  c19[appjs]
  c71[extractTime]
  c25[cmdDone]
  c60[systempromptjs]
  c58[nodepath]
  c18[cleanupTransitionClasses]
  c62[schedulerintegrationjs]
  c41[start]
  c26[cmdStats]
  c57[nodefs]
  c96[submitFeedback]
  c91[safeExec]
  c28[checkErr]
  c69[nodechild_process]
  c29[saveStore]
  c12[generateWindsurfInstructi..]
  c3[parseSkillMarkdown]
  c31[encodingjson]
  c11[convertSkillToWindsurf]
  c35[os]
  c102[saveInbound]
  c81[listTasks]
  c100[feedbackstorejs]
  c84[schedulerintegrationjs]
  c55[toolDefinitions]
  c97[getFeedbackStats]
  c43[log]

  c0 -.-> c1
  c2 --> c3
  c2 --> c4
  c5 --> c3
  c5 --> c4
  c6 --> c4
  c7 --> c2
  c7 --> c5
  c7 --> c6
  c8 --> c3
  c9 --> c3
  c7 --> c8
  c7 --> c9
  c7 --> c10
  c11 --> c3
  c11 --> c12
  c13 --> c3
  c7 --> c11
  c7 --> c13
  c14 --> c15
  c16 --> c17
  c16 --> c17
  c15 --> c16
  c15 --> c18
  c15 --> c16
  c15 --> c18
  c15 --> c18
  c15 --> c18
  c15 --> c18
  c15 --> c16
  c19 --> c14
  c19 --> c15
  c20 --> c21
  c20 --> c22
  c20 --> c23
  c20 --> c24
  c20 --> c25
  c20 --> c26
  c20 --> c21
  c20 --> c21
  c23 --> c27
  c23 --> c28
  c23 --> c28
  c23 --> c29
  c24 --> c27
  c24 --> c28
  c25 --> c27
  c25 --> c28
  c25 --> c28
  c25 --> c29
  c26 --> c27
  c26 --> c28
  c30 -.-> c31
  c30 -.-> c32
  c30 -.-> c33
  c30 -.-> c34
  c30 -.-> c35
  c30 -.-> c36
  c30 -.-> c37
  c38 --> c39
  c38 --> c40
  c41 --> c42
  c41 --> c43
  c44 --> c45
  c44 --> c43
  c46 --> c47
  c46 --> c47
  c46 --> c48
  c46 --> c45
  c46 --> c39
  c46 --> c40
  c46 --> c49
  c46 --> c47
  c46 --> c45
  c49 --> c50
  c49 --> c51
  c49 --> c52
  c51 --> c53
  c51 --> c54
  c51 --> c43
  c51 --> c43
  c53 --> c55
  c54 --> c55
  c56 -.-> c57
  c56 -.-> c58
  c56 -.-> c59
  c56 -.-> c60
  c56 -.-> c61
  c56 -.-> c62
  c63 --> c64
  c39 --> c65
  c39 --> c66
  c39 --> c66
  c39 --> c67
  c39 --> c68
  c39 --> c63
  c61 -.-> c57
  c61 -.-> c58
  c61 -.-> c69
  c70 --> c71
  c72 --> c73
  c74 --> c50
  c75 --> c72
  c76 -.-> c57
  c76 -.-> c58
  c77 --> c78
  c79 --> c80
  c79 --> c81
  c79 --> c77
  c79 --> c82
  c79 --> c77
  c79 --> c70
  c79 --> c83
  c79 --> c77
  c79 --> c70
  c79 --> c83
  c79 --> c77
  c79 --> c70
  c79 --> c83
  c79 --> c77
  c48 --> c79
  c84 -.-> c85
  c84 -.-> c86
  c42 --> c43
  c42 --> c43
  c45 --> c43
  c83 --> c87
  c83 --> c45
  c82 --> c45
  c88 --> c43
  c88 --> c45
  c88 --> c43
  c88 --> c43
  c89 --> c90
  c89 --> c88
  c41 --> c42
  c41 --> c89
  c41 --> c43
  c44 --> c45
  c44 --> c43
  c78 --> c42
  c86 -.-> c57
  c86 -.-> c58
  c86 -.-> c69
  c40 --> c55
  c60 -.-> c59
  c91 --> c92
  c91 --> c92
  c93 --> c94
  c52 --> c91
  c52 --> c91
  c52 --> c91
  c52 --> c39
  c52 --> c64
  c52 --> c39
  c52 --> c70
  c52 --> c78
  c52 --> c83
  c52 --> c78
  c52 --> c81
  c52 --> c78
  c52 --> c82
  c52 --> c70
  c52 --> c95
  c52 --> c96
  c52 --> c97
  c52 --> c98
  c52 --> c74
  c59 -.-> c69
  c59 -.-> c57
  c59 -.-> c58
  c59 -.-> c61
  c59 -.-> c86
  c59 -.-> c85
  c59 -.-> c99
  c59 -.-> c100
  c98 --> c97
  c100 -.-> c57
  c100 -.-> c58
  c100 -.-> c101
  c102 --> c43
  c102 --> c46
  c102 --> c43
  c103 --> c104
  c103 --> c43
  c103 --> c43
  c103 --> c43
  c20 --> c43
  c20 --> c43
  c20 --> c104
  c20 --> c43
  c20 --> c75
  c20 --> c43
  c20 --> c43
  c20 --> c102
  c20 --> c43
  c20 --> c43
  c20 --> c41
  c20 --> c43
  c20 --> c78

