flowchart LR
  classDef default fill:#1a2035,stroke:#00bfff,color:#e0e0e0
  classDef func fill:#1a2035,stroke:#00ff88,color:#e0e0e0
  classDef method fill:#1a2035,stroke:#ffaa00,color:#e0e0e0

  c96[WriteAuditEntry]
  c43[appjs]
  c141[handleModelPickerKey]
  c31[HitlModaltsx]
  c107[sort]
  c39[buildDots]
  c24[Apptsx]
  c2[convertSkillToAntigravity]
  c32[Marketplacetsx]
  c115[TestLoadRouterConfig_Miss..]
  c90[nltimeparserjs]
  c54[maingo]
  c99[cryptosha256]
  c47[cmdAdd]
  c108[TestNormalizeFloat64]
  c88[handleIncomingMessage]
  c122[TestAllBindingsCount]
  c16[path]
  c76[watchSessionState]
  c124[ProviderList]
  c8[convertSkillToCodex]
  c29[GlobalHealthtsx]
  c56[errors]
  c104[AllBindings]
  c130[config_testgo]
  c143[handleAdminAuthKey]
  c89[schedulerintegrationjs]
  c3[parseSkillMarkdown]
  c114[TestLoadRouterConfig_Inva..]
  c5[generateAGENTSmd]
  c67[getCurrentSessionId]
  c49[cmdDone]
  c131[testing]
  c138[handleChangeDefaultsKey]
  c92[getMachineGUID]
  c95[IsTrustedPC]
  c57[flag]
  c60[pathfilepath]
  c4[mapSkillToAgentRole]
  c113[LoadRouterConfig]
  c20[getRealMetrics]
  c101[net]
  c37[viteconfigts]
  c62[findStateInDir]
  c134[Update]
  c41[pad]
  c69[detectMechanismFromModel]
  c105[ResolveBinding]
  c59[os]
  c22[getGitStats]
  c100[encodinghex]
  c118[TestResolveBinding_Defaul..]
  c77[parseNLToCron]
  c91[GetPcFingerprint]
  c128[LoadCloudAgents]
  c28[AgentMessagetsx]
  c111[Error]
  c12[generateWindsurfInstructi..]
  c85[handleScheduleCommand]
  c135[handleKey]
  c45[printHelp]
  c18[srctypesdashboardjs]
  c123[TestProviderList]
  c64[getAgentModel]
  c17[url]
  c71[getHistory]
  c38[vitejspluginreact]
  c23[realdatats]
  c112[TestLoadRouterConfig]
  c78[extractTime]
  c10[generateProxyServer]
  c34[TaskControltsx]
  c14[globalhealthapits]
  c86[formatScheduleList]
  c98[authgo]
  c145[showAdminOptions]
  c33[SessionTimelinetsx]
  c140[handleEditAgentKey]
  c27[lucidereact]
  c61[time]
  c121[HasCustomBindings]
  c87[sched]
  c11[convertSkillToWindsurf]
  c15[child_process]
  c30[typesdashboard]
  c136[handleOverviewKey]
  c132[initialModel]
  c13[generateWindsurfConfig]
  c52[checkErr]
  c93[getMacAddress]
  c53[saveStore]
  c25[react]
  c19[mcpmetricsapits]
  c36[render]
  c66[readDir]
  c110[TestAgentCodesSorted]
  c103[strings]
  c125[TestProviderEntryLabel]
  c127[TestLoadCloudAgents]
  c142[handleTemperatureKey]
  c109[NormalizeFloat64]
  c102[osexec]
  c82[pluginloaderjs]
  c44[main]
  c97[FindRepoRoot]
  c26[reactrouterdom]
  c139[handlePerAgentKey]
  c81[reloadPlugins]
  c116[TestSaveRouterConfig]
  c120[TestHasCustomBindings]
  c106[configgo]
  c6[generateMissionYaml]
  c68[getLiveSession]
  c133[Init]
  c94[getHostname]
  c137[handleAllSameKey]
  c74[getCommitTimeline]
  c129[TestLoadCloudAgents_Inval..]
  c46[defaultDataPath]
  c65[collectSessions]
  c75[generateMetrics]
  c48[cmdList]
  c119[TestResolveBinding_Overri..]
  c51[loadStore]
  c9[generateToolsArray]
  c35[maintsx]
  c0[grindts]
  c70[getMechanismHistory]
  c50[cmdStats]
  c117[SaveRouterConfig]
  c80[getPluginDir]
  c1[fs]
  c42[cleanupTransitionClasses]
  c73[runGh]
  c84[nodepath]
  c79[scanPlugins]
  c40[updateChrome]
  c63[readJson]
  c144[handleAdminPasswordKey]
  c58[fmt]
  c7[adapterjs]
  c55[encodingjson]
  c126[Label]
  c21[countSkills]
  c83[nodefs]
  c72[runGit]

  c0 -.-> c1
  c2 --> c3
  c2 --> c4
  c5 --> c3
  c5 --> c4
  c6 --> c4
  c7 --> c2
  c7 --> c5
  c7 --> c6
  c8 --> c3
  c9 --> c3
  c7 --> c8
  c7 --> c9
  c7 --> c10
  c11 --> c3
  c11 --> c12
  c13 --> c3
  c7 --> c11
  c7 --> c13
  c14 -.-> c15
  c14 -.-> c16
  c14 -.-> c17
  c14 -.-> c1
  c14 -.-> c18
  c19 -.-> c1
  c19 -.-> c16
  c20 --> c21
  c20 --> c22
  c23 -.-> c1
  c23 -.-> c16
  c23 -.-> c17
  c23 -.-> c15
  c24 -.-> c25
  c24 -.-> c26
  c24 -.-> c27
  c28 -.-> c27
  c29 -.-> c27
  c29 -.-> c30
  c31 -.-> c27
  c32 -.-> c25
  c32 -.-> c27
  c33 -.-> c27
  c34 -.-> c27
  c35 --> c36
  c37 -.-> c38
  c39 --> c36
  c40 --> c41
  c40 --> c41
  c36 --> c40
  c36 --> c42
  c36 --> c40
  c36 --> c42
  c36 --> c42
  c36 --> c42
  c36 --> c42
  c36 --> c40
  c43 --> c39
  c43 --> c36
  c44 --> c45
  c44 --> c46
  c44 --> c47
  c44 --> c48
  c44 --> c49
  c44 --> c50
  c44 --> c45
  c44 --> c45
  c47 --> c51
  c47 --> c52
  c47 --> c52
  c47 --> c53
  c48 --> c51
  c48 --> c52
  c49 --> c51
  c49 --> c52
  c49 --> c52
  c49 --> c53
  c50 --> c51
  c50 --> c52
  c54 -.-> c55
  c54 -.-> c56
  c54 -.-> c57
  c54 -.-> c58
  c54 -.-> c59
  c54 -.-> c60
  c54 -.-> c61
  c62 --> c63
  c64 --> c63
  c65 --> c66
  c65 --> c62
  c65 --> c67
  c67 --> c66
  c68 --> c67
  c68 --> c63
  c68 --> c69
  c70 --> c69
  c70 --> c69
  c70 --> c63
  c71 --> c65
  c22 --> c72
  c22 --> c72
  c22 --> c72
  c22 --> c72
  c22 --> c73
  c22 --> c73
  c22 --> c72
  c22 --> c72
  c74 --> c72
  c75 --> c65
  c75 --> c71
  c75 --> c71
  c75 --> c71
  c75 --> c68
  c75 --> c22
  c75 --> c74
  c76 --> c67
  c76 --> c68
  c77 --> c78
  c79 --> c80
  c81 --> c79
  c82 -.-> c83
  c82 -.-> c84
  c85 --> c77
  c85 --> c77
  c85 --> c77
  c85 --> c86
  c85 --> c87
  c85 --> c87
  c85 --> c87
  c85 --> c87
  c85 --> c87
  c88 --> c85
  c89 -.-> c90
  c91 --> c92
  c91 --> c93
  c91 --> c94
  c95 --> c91
  c96 --> c97
  c96 --> c91
  c96 --> c94
  c98 -.-> c99
  c98 -.-> c100
  c98 -.-> c58
  c98 -.-> c101
  c98 -.-> c59
  c98 -.-> c102
  c98 -.-> c103
  c104 --> c105
  c106 -.-> c55
  c106 -.-> c58
  c106 -.-> c59
  c106 -.-> c107
  c106 -.-> c103
  c108 --> c109
  c110 --> c111
  c112 --> c113
  c112 --> c111
  c114 --> c113
  c114 --> c111
  c115 --> c113
  c115 --> c111
  c116 --> c117
  c118 --> c105
  c119 --> c105
  c120 --> c121
  c120 --> c111
  c120 --> c121
  c120 --> c111
  c122 --> c104
  c123 --> c124
  c125 --> c126
  c125 --> c126
  c125 --> c126
  c125 --> c126
  c125 --> c126
  c127 --> c128
  c127 --> c111
  c129 --> c128
  c129 --> c111
  c130 -.-> c55
  c130 -.-> c59
  c130 -.-> c107
  c130 -.-> c131
  c132 --> c97
  c133 --> c113
  c133 --> c128
  c134 --> c135
  c134 --> c104
  c134 --> c124
  c134 --> c95
  c134 --> c121
  c135 --> c136
  c135 --> c137
  c135 --> c138
  c135 --> c139
  c135 --> c140
  c135 --> c141
  c135 --> c142
  c135 --> c143
  c135 --> c144
  c136 --> c145

