# PodDisruptionBudget for {{project-name}}

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: '{{project-name}}-pdb'
  namespace: '{{namespace}}'
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: '{{project-name}}'
