param(
    [string]$TaskName,
    [switch]$SkipReview,
    [switch]$SkipTests,
    [switch]$SkipAudit,
    [switch]$SkipGovernance,
    [switch]$SkipRotation,
    [int]$MaxArtifacts = 1,
    [int]$MaxLocalArtifacts = 30,
    [switch]$AllowUnpublishedClose,
    [switch]$Force
)

$ErrorActionPreference = 'Stop'
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = (Resolve-Path (Join-Path $scriptDir '..\..')).Path
$wfScript = Join-Path $scriptDir 'wf.ps1'
$governanceScript = Join-Path $repoRoot 'scripts\diagnostics\validate-script-governance.ps1'
$rotateScript = Join-Path $scriptDir 'rotate-artifacts.ps1'

function Write-Step {
    param([string]$Message)
    Write-Host "`n=== $Message ===" -ForegroundColor Cyan
}

function Write-Ok {
    param([string]$Message)
    Write-Host "[OK] $Message" -ForegroundColor Green
}

function Write-Warn {
    param([string]$Message)
    Write-Host "[WARN] $Message" -ForegroundColor Yellow
}

function Invoke-LocalPowerShellScript {
    param(
        [string]$ScriptPath,
        [string[]]$ScriptArgs = @()
    )

    & $ScriptPath @ScriptArgs
}

function Get-ResultLabel {
    param([bool]$Ran, [int]$Code)
    if (-not $Ran) { return 'SKIPPED' }
    if ($Code -eq 0) { return 'PASS' }
    return 'FAIL'
}

Set-Location $repoRoot

$branch = git rev-parse --abbrev-ref HEAD 2>$null
if ([string]::IsNullOrWhiteSpace($branch)) { $branch = 'unknown' }

$reviewRan = $false
$reviewCode = 0
$auditRan = $false
$auditCode = 0
$govRan = $false
$govCode = 0

if (-not $SkipReview) {
    Write-Step 'Session closure review'
    $reviewRan = $true
    $reviewArgs = @('review')
    if ($SkipTests) { $reviewArgs += '-SkipTests' }
    Invoke-LocalPowerShellScript -ScriptPath $wfScript -ScriptArgs $reviewArgs
    $reviewCode = $LASTEXITCODE
    if ($reviewCode -ne 0) {
        Write-Warn 'Review reported failures.'
    }
}

if (-not $SkipAudit) {
    Write-Step 'Session closure audit'
    $auditRan = $true
    Invoke-LocalPowerShellScript -ScriptPath $wfScript -ScriptArgs @('audit')
    $auditCode = $LASTEXITCODE
    if ($auditCode -ne 0) {
        Write-Warn 'Audit generation reported failures.'
    }
}

if (-not $SkipGovernance -and (Test-Path $governanceScript)) {
    Write-Step 'Session closure governance check'
    $govRan = $true
    Invoke-LocalPowerShellScript -ScriptPath $governanceScript -ScriptArgs @('-SkipFallbackTests')
    $govCode = $LASTEXITCODE
    if ($govCode -ne 0) {
        Write-Warn 'Governance validation reported failures.'
    }
}

$sessionsDir = Join-Path $repoRoot 'docs\sessions'
New-Item -ItemType Directory -Path $sessionsDir -Force | Out-Null

$dateTag = Get-Date -Format 'yyyy-MM-dd-HHmmss'
$outputPath = Join-Path $sessionsDir ("{0}-delivery-closure.md" -f $dateTag)

$taskLine = if ([string]::IsNullOrWhiteSpace($TaskName)) { '- Task scope: not specified' } else { "- Task scope: $TaskName" }
$gitStatus = git status --short 2>$null
$gitState = if ([string]::IsNullOrWhiteSpace(($gitStatus -join '').Trim())) { 'clean' } else { 'has uncommitted changes' }
$hasUncommittedChanges = ($gitState -ne 'clean')

$upstream = git rev-parse --abbrev-ref --symbolic-full-name "@{upstream}" 2>$null
$hasUpstream = -not [string]::IsNullOrWhiteSpace($upstream)
$commitsAhead = 0
$commitsBehind = 0
if ($hasUpstream) {
    $aheadBehind = git rev-list --count --left-right "@{upstream}...HEAD" 2>$null
    if (-not [string]::IsNullOrWhiteSpace($aheadBehind)) {
        $parts = $aheadBehind -split '\s+'
        if ($parts.Count -ge 2) {
            $commitsBehind = [int]$parts[0]
            $commitsAhead = [int]$parts[1]
        }
    }
}

$hasUnpublishedCommits = ($commitsAhead -gt 0) -or (-not $hasUpstream)
$publishState = if ($hasUnpublishedCommits) { 'has unpublished commits or no upstream tracking' } else { 'synced with upstream' }

$owner = git config user.name 2>$null
if ([string]::IsNullOrWhiteSpace($owner)) { $owner = 'unknown' }
$latestCommit = git log -1 --pretty=oneline 2>$null
if ([string]::IsNullOrWhiteSpace($latestCommit)) { $latestCommit = 'none' }

$content = @"
# Delivery Closure

Date: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
Owner: $owner
Branch: $branch
$taskLine

## 1. Executed Checks

- Review: $(Get-ResultLabel -Ran $reviewRan -Code $reviewCode)
- Audit: $(Get-ResultLabel -Ran $auditRan -Code $auditCode)
- Governance: $(Get-ResultLabel -Ran $govRan -Code $govCode)

## 2. Repository State

- Git state: $gitState
- Publish state: $publishState
- Upstream branch: $(if ($hasUpstream) { $upstream } else { 'none' })
- Commits ahead: $commitsAhead
- Commits behind: $commitsBehind
- Latest commit: $latestCommit

## 3. Pending Actions

- [ ] Confirm PR checks are green.
- [ ] Confirm documentation updates for behavior changes.
- [ ] Proceed with publish or continue implementation.

## 4. Notes

- This artifact was generated by `wf.ps1 end-session`.
- Commands can be skipped with: `-SkipReview`, `-SkipAudit`, `-SkipGovernance`.
"@

$content | Out-File -FilePath $outputPath -Encoding UTF8
Write-Ok "Delivery closure created: $outputPath"

if (-not $SkipRotation -and (Test-Path $rotateScript)) {
    Write-Step "Artifact rotation"
    & $rotateScript -MaxRepoFiles $MaxArtifacts -MaxLocalFiles $MaxLocalArtifacts | Out-Null
    Write-Ok "Artifact rotation complete"
}

$hasFailure = ($reviewRan -and $reviewCode -ne 0) -or ($auditRan -and $auditCode -ne 0) -or ($govRan -and $govCode -ne 0)
if ($hasFailure -and -not $Force) {
    Write-Warn 'Session closure completed with failed checks. Re-run with -Force to bypass failure exit.'
    exit 1
}

$hasPublicationRisk = $hasUncommittedChanges -or $hasUnpublishedCommits
if ($hasPublicationRisk -and -not $AllowUnpublishedClose -and -not $Force) {
    Write-Warn 'Session closure blocked by publication policy: there are local/unpublished changes.'
    Write-Warn 'Use wf.ps1 publish (recommended), or re-run end-session with -AllowUnpublishedClose to accept the risk.'
    exit 2
}

Write-Ok 'Session closure completed.'
exit 0
