# generate-session-artifacts.ps1
# Generates audit, budget, and telemetry files on session close
# File naming: <report-name>_<yyyy-MM-dd-HHmmss>.<ext>

param(
    [string]$SessionId,
    [string]$SessionFile,
    [switch]$Force
)

$ErrorActionPreference = 'Stop'
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectRoot = Resolve-Path (Join-Path $scriptDir "..\..")
$auditDir = Join-Path $projectRoot ".audit"

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $color = switch ($Level) {
        "OK" { "Green" }
        "WARN" { "Yellow" }
        "ERROR" { "Red" }
        default { "Gray" }
    }
    Write-Host "[$Level] $Message" -ForegroundColor $color
}

function Ensure-AuditDirs {
    $dirs = @("sessions", "audits", "ai-activity", "code-reviews", "metrics", "reports", "budgets", "telemetry", "pr-audits")
    foreach ($dir in $dirs) {
        $path = Join-Path $auditDir $dir
        if (-not (Test-Path $path)) {
            New-Item -ItemType Directory -Path $path -Force | Out-Null
        }
    }
}

function Get-MachineId {
    $id = $env:COMPUTERNAME
    if (Test-Path "C:\Users\.machine-id") {
        $id = Get-Content "C:\Users\.machine-id" -Raw -ErrorAction SilentlyContinue
    }
    return $id.Trim()
}

function Get-UserName {
    return $env:USERNAME
}

function New-AuditFile {
    param([string]$SessionId, [string]$SessionFile)
    
    $timestamp = Get-Date -Format "yyyy-MM-ddTHH:mm:ss"
    $dateTag = Get-Date -Format "yyyy-MM-dd-HHmmss"
    
    $auditFileName = "audit_$dateTag.md"
    $auditPath = Join-Path $auditDir "audits\$auditFileName"
    
    $sessionData = $null
    $duration = 0
    $filesModified = 0
    $linesAdded = 0
    $linesRemoved = 0
    $commandsExecuted = 0
    $errors = 0
    $totalRequests = 0
    $totalTokens = 0
    
    if ($SessionFile -and (Test-Path $SessionFile)) {
        $sessionData = Get-Content $SessionFile -Raw | ConvertFrom-Json
        $duration = $sessionData.metrics.duration
        $filesModified = $sessionData.activity.filesModified.Count
        $linesAdded = $sessionData.activity.linesAdded
        $linesRemoved = $sessionData.activity.linesRemoved
        $commandsExecuted = $sessionData.activity.commandsExecuted.Count
        $errors = $sessionData.activity.errors.Count
        
        foreach ($tool in $sessionData.aiTools.PSObject.Properties) {
            $totalRequests += $tool.Value.requests
            $totalTokens += $tool.Value.tokensEstimated
        }
    }
    
    $auditContent = @"
# Session Audit - $dateTag

**Session ID:** $SessionId  
**Timestamp:** $timestamp  
**Project:** $(Split-Path $projectRoot -Leaf)  
**User:** $(Get-UserName)@$(Get-MachineId)  

---

## Executive Summary

| Metric | Value |
|--------|-------|
| Duration | $([math]::Round($duration, 1)) min |
| Total Requests | $totalRequests |
| Total Tokens | $([math]::Round($totalTokens / 1000, 1))K |
| Files Modified | $filesModified |
| Lines Added | $linesAdded |
| Lines Removed | $linesRemoved |
| Commands Executed | $commandsExecuted |
| Errors | $errors |

---

## Activity Details

### Files Modified
"@
    
    if ($sessionData -and $sessionData.activity.filesModified.Count -gt 0) {
        $auditContent += "`n`n"
        foreach ($file in $sessionData.activity.filesModified) {
            $auditContent += "- $file`n"
        }
    } else {
        $auditContent += "`n\nNo files modified.`n"
    }
    
    $auditContent += @"

### Commands Executed

"@
    
    if ($sessionData -and $sessionData.activity.commandsExecuted.Count -gt 0) {
        $auditContent += "`n`n"
        foreach ($cmd in $sessionData.activity.commandsExecuted) {
            $auditContent += "- $cmd`n"
        }
    } else {
        $auditContent += "No commands recorded.`n"
    }
    
    $auditContent += @"

### Errors

"@
    
    if ($sessionData -and $sessionData.activity.errors.Count -gt 0) {
        $auditContent += "`n`n"
        foreach ($err in $sessionData.activity.errors) {
            $auditContent += "- **$($err.timestamp):** $($err.message)`n"
        }
    } else {
        $auditContent += "No errors recorded.`n"
    }
    
    $auditContent += @"

---

## AI Tools Usage

| Tool | Requests | Tokens (est.) |
|------|----------|---------------|
"@
    
    if ($sessionData) {
        foreach ($tool in $sessionData.aiTools.PSObject.Properties) {
            $auditContent += "| $($tool.Name) | $($tool.Value.requests) | $([math]::Round($tool.Value.tokensEstimated / 1000, 1))K |`n"
        }
    } else {
        $auditContent += "| N/A | 0 | 0 |`n"
    }
    
    $auditContent += @"

---

## Validation

| Check | Status |
|-------|--------|
"@
    
    if ($sessionData) {
        $auditContent += "| Validation Passed | $(if ($sessionData.validation.passed) { '✅' } else { '❌' }) |`n"
    } else {
        $auditContent += "| Validation | N/A |`n"
    }
    
    $auditContent += @"

---

*Generated by generate-session-artifacts.ps1*
"@
    
    $auditContent | Out-File -FilePath $auditPath -Encoding UTF8
    Write-Log "Audit file generated: $auditPath" "OK"
    
    return $auditPath
}

function New-BudgetFile {
    param([hashtable]$Summary)
    
    $timestamp = Get-Date -Format "yyyy-MM-ddTHH:mm:ss"
    $dateTag = Get-Date -Format "yyyy-MM-dd-HHmmss"
    
    $budgetFileName = "budget_$dateTag.md"
    $budgetCsvName = "budget_$dateTag.csv"
    $budgetPath = Join-Path $auditDir "budgets\$budgetFileName"
    $budgetCsvPath = Join-Path $auditDir "budgets\$budgetCsvName"
    
    $costPer1MTokens = 10.0
    $costPerToken = $costPer1MTokens / 1000000
    $estimatedCost = [math]::Round($Summary.totalTokens * $costPerToken, 4)
    
    $tokensByTool = $Summary.TokensByTool
    if (-not $tokensByTool) { $tokensByTool = @{} }
    
    $budgetContent = @"
# Session Budget - $dateTag

**Session ID:** $Summary.SessionId  
**Timestamp:** $timestamp  
**Project:** $(Split-Path $projectRoot -Leaf)  

---

## Cost Summary

| Metric | Value |
|--------|-------|
| Total Requests | $($Summary.totalRequests) |
| Total Tokens | $([math]::Round($Summary.totalTokens / 1000, 1))K |
| Cost per 1M Tokens | `$$costPer1MTokens |
| **Estimated Cost** | **`$$estimatedCost** |

---

## Budget Status

| Budget | Limit | Used | Remaining |
|--------|-------|------|-----------|
| Daily | `$$50.00 | `$$estimatedCost | `$$([math]::Round(50.0 - $estimatedCost, 2)) |
| Monthly | `$$500.00 | `$$estimatedCost | `$$([math]::Round(500.0 - $estimatedCost, 2)) |

---

## Usage by Tool

| Tool | Tokens | Cost (est.) |
|------|--------|-------------|
"@
    
    if ($tokensByTool.Count -gt 0) {
        foreach ($tool in $tokensByTool.GetEnumerator()) {
            $toolCost = [math]::Round($tool.Value * $costPerToken, 4)
            $budgetContent += "| $($tool.Key) | $([math]::Round($tool.Value / 1000, 1))K | `$$toolCost |`n"
        }
    } else {
        $budgetContent += "| N/A | 0 | `$$0.00 |`n"
    }
    
    $alerts = @()
    if ($estimatedCost -gt 5.0) {
        $alerts += "⚠️ Session cost exceeds $5 threshold"
    }
    if ($estimatedCost -gt 20.0) {
        $alerts += "🚨 Session cost exceeds $20 threshold - review required"
    }
    
    if ($alerts.Count -gt 0) {
        $budgetContent += @"

---

## Alerts

"@
        foreach ($alert in $alerts) {
            $budgetContent += "- $alert`n"
        }
    }
    
    $budgetContent += @"

---

## CSV Export

Raw data available in: `budget_$dateTag.csv`

---

*Generated by generate-session-artifacts.ps1*
"@
    
    $budgetContent | Out-File -FilePath $budgetPath -Encoding UTF8
    
    $csvData = @{
        session_id = $Summary.SessionId
        timestamp = $timestamp
        total_requests = $Summary.totalRequests
        total_tokens = $Summary.totalTokens
        cost_per_1m = $costPer1MTokens
        estimated_cost = $estimatedCost
        daily_limit = 50.0
        monthly_limit = 500.0
    }
    
    $csvData | ConvertTo-Csv -NoTypeInformation | Out-File -FilePath $budgetCsvPath -Encoding UTF8
    
    Write-Log "Budget files generated: $budgetPath, $budgetCsvPath" "OK"
    
    return $budgetPath
}

function New-TelemetryFile {
    param([hashtable]$Summary)
    
    $timestamp = Get-Date -Format "yyyy-MM-ddTHH:mm:ss"
    $dateTag = Get-Date -Format "yyyy-MM-dd-HHmmss"
    
    $telemetryFileName = "telemetry_$dateTag.md"
    $telemetryCsvName = "telemetry_$dateTag.csv"
    $telemetryPath = Join-Path $auditDir "telemetry\$telemetryFileName"
    $telemetryCsvPath = Join-Path $auditDir "telemetry\$telemetryCsvName"
    
    $requestsPerMinute = [math]::Round($Summary.totalRequests / [math]::Max($Summary.Duration, 1), 2)
    $tokensPerMinute = [math]::Round($Summary.totalTokens / [math]::Max($Summary.Duration, 1), 2)
    
    $mostUsedTool = $null
    if ($Summary.TokensByTool -and $Summary.TokensByTool.Count -gt 0) {
        $mostUsedTool = ($Summary.TokensByTool.GetEnumerator() | Sort-Object { $_.Value } -Descending | Select-Object -First 1).Key
    }
    
    $telemetryContent = @"
# Session Telemetry - $dateTag

**Session ID:** $Summary.SessionId  
**Timestamp:** $timestamp  
**Project:** $(Split-Path $projectRoot -Leaf)  
**User:** $(Get-UserName)@$(Get-MachineId)  

---

## Performance Metrics

| Metric | Value |
|--------|-------|
| Session Duration | $([math]::Round($Summary.Duration, 1)) min |
| Requests per Minute | $requestsPerMinute |
| Tokens per Minute | $tokensPerMinute |
| Most Used AI Tool | $(if ($mostUsedTool) { $mostUsedTool } else { "N/A" }) |

---

## Development Activity

| Category | Count |
|----------|-------|
| Files Created | $($Summary.FilesCreated) |
| Files Modified | $($Summary.FilesModified) |
| Files Deleted | $($Summary.FilesDeleted) |
| Lines Added | $($Summary.LinesAdded) |
| Lines Removed | $($Summary.LinesRemoved) |
| Commands Executed | $($Summary.CommandsExecuted) |
| Errors | $($Summary.Errors) |

---

## AI Tools Usage

| Tool | Tokens | % of Total |
|------|--------|------------|
"@
    
    $totalTokens = $Summary.totalTokens
    if ($Summary.TokensByTool -and $Summary.TokensByTool.Count -gt 0) {
        foreach ($tool in ($Summary.TokensByTool.GetEnumerator() | Sort-Object { $_.Value } -Descending)) {
            $percent = [math]::Round(($tool.Value / [math]::Max($totalTokens, 1)) * 100, 1)
            $telemetryContent += "| $($tool.Key) | $([math]::Round($tool.Value / 1000, 1))K | $percent% |`n"
        }
    } else {
        $telemetryContent += "| N/A | 0 | 0% |`n"
    }
    
    $telemetryContent += @"

---

## Quality Metrics

| Check | Status |
|-------|--------|
| Validation Passed | $(if ($Summary.ValidationPassed) { '✅' } else { '❌' }) |
| Tests Run | $($Summary.TestsRun) |
| Tests Passed | $($Summary.TestsPassed) |
| Code Coverage | N/A |

---

## Session Mode

**Mode:** $(if ($Summary.Mode) { $Summary.Mode } else { "unknown" })

---

## CSV Export

Raw data available in: `telemetry_$dateTag.csv`

---

*Generated by generate-session-artifacts.ps1*
"@
    
    $telemetryContent | Out-File -FilePath $telemetryPath -Encoding UTF8
    
    $csvData = @{
        session_id = $Summary.SessionId
        timestamp = $timestamp
        duration_minutes = $Summary.Duration
        total_requests = $Summary.totalRequests
        total_tokens = $Summary.totalTokens
        requests_per_minute = $requestsPerMinute
        tokens_per_minute = $tokensPerMinute
        files_created = $Summary.FilesCreated
        files_modified = $Summary.FilesModified
        files_deleted = $Summary.FilesDeleted
        lines_added = $Summary.LinesAdded
        lines_removed = $Summary.LinesRemoved
        commands_executed = $Summary.CommandsExecuted
        errors = $Summary.Errors
        validation_passed = $Summary.ValidationPassed
        most_used_tool = $mostUsedTool
        mode = $Summary.Mode
    }
    
    $csvData | ConvertTo-Csv -NoTypeInformation | Out-File -FilePath $telemetryCsvPath -Encoding UTF8
    
    Write-Log "Telemetry files generated: $telemetryPath, $telemetryCsvPath" "OK"
    
    return $telemetryPath
}

function Invoke-GenerateArtifacts {
    param(
        [string]$SessionId,
        [string]$SessionFile
    )
    
    Write-Log "Starting session artifacts generation..." "INFO"
    
    Ensure-AuditDirs
    
    $summary = @{
        SessionId = $SessionId
        StartTime = (Get-Date).AddMinutes(-30).ToString("yyyy-MM-ddTHH:mm:ss")
        Duration = 0
        totalRequests = 0
        totalTokens = 0
        TokensByTool = @{}
        FilesCreated = 0
        FilesModified = 0
        FilesDeleted = 0
        LinesAdded = 0
        LinesRemoved = 0
        CommandsExecuted = 0
        Errors = 0
        ValidationPassed = $true
        Mode = "unknown"
    }
    
    if ($SessionFile -and (Test-Path $SessionFile)) {
        $sessionData = Get-Content $SessionFile -Raw | ConvertFrom-Json
        
        $summary.StartTime = $sessionData.timestamp
        $summary.Duration = $sessionData.metrics.duration
        $summary.FilesCreated = $sessionData.metrics.filesCreated
        $summary.FilesModified = $sessionData.metrics.filesUpdated
        $summary.FilesDeleted = $sessionData.metrics.filesDeleted
        $summary.LinesAdded = $sessionData.activity.linesAdded
        $summary.LinesRemoved = $sessionData.activity.linesRemoved
        $summary.CommandsExecuted = $sessionData.activity.commandsExecuted.Count
        $summary.Errors = $sessionData.activity.errors.Count
        $summary.ValidationPassed = $sessionData.validation.passed
        $summary.Mode = $sessionData.mode
        
        foreach ($tool in $sessionData.aiTools.PSObject.Properties) {
            $summary.totalRequests += $tool.Value.requests
            $summary.totalTokens += $tool.Value.tokensEstimated
            $summary.TokensByTool[$tool.Name] = $tool.Value.tokensEstimated
        }
    } else {
        Write-Log "No session file provided, using default values" "WARN"
    }
    
    $auditPath = New-AuditFile -SessionId $SessionId -SessionFile $SessionFile
    $budgetPath = New-BudgetFile -Summary $summary
    $telemetryPath = New-TelemetryFile -Summary $summary
    
    Write-Log "" "INFO"
    Write-Log "Session artifacts generation completed" "OK"
    Write-Log "  Audit: $auditPath" "INFO"
    Write-Log "  Budget: $budgetPath" "INFO"
    Write-Log "  Telemetry: $telemetryPath" "INFO"
    
    return @{
        Audit = $auditPath
        Budget = $budgetPath
        Telemetry = $telemetryPath
    }
}

if ($Force) {
    $sessionId = if ($SessionId) { $SessionId } else { "unknown" }
    $sessionFile = if ($SessionFile) { $SessionFile } else { $env:WFS_SESSION_FILE }
    
    Invoke-GenerateArtifacts -SessionId $sessionId -SessionFile $sessionFile
} else {
    Write-Host "Usage: generate-session-artifacts.ps1 -Force [-SessionId XXXX] [-SessionFile <path>]" -ForegroundColor Yellow
    Write-Host "  -Force      Generate artifacts immediately" -ForegroundColor Gray
    Write-Host "  -SessionId  Session ID (optional, auto-detected from env)" -ForegroundColor Gray
    Write-Host "  -SessionFile Path to session JSON file (optional)" -ForegroundColor Gray
}
