# generate-pr-artifacts.ps1
# Generates audit, budget, and telemetry files when creating a PR or pushing to remote
# File naming: <report-name>_<yyyy-MM-dd-HHmmss>.<ext>

param(
    [string]$BranchName,
    [string]$PRTitle,
    [switch]$PrePush,
    [switch]$PostPush
)

$ErrorActionPreference = 'Stop'
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectRoot = Resolve-Path (Join-Path $scriptDir "..\..")
Set-Location $projectRoot

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $color = switch ($Level) {
        "OK" { "Green" }
        "WARN" { "Yellow" }
        "ERROR" { "Red" }
        default { "Gray" }
    }
    Write-Host "[$Level] $Message" -ForegroundColor $color
}

function Get-CurrentBranch {
    return git rev-parse --abbrev-ref HEAD 2>$null
}

function Get-CommitCount {
    param([string]$SinceDate)
    $since = if ($SinceDate) { $SinceDate } else { "1 week ago" }
    $count = git log --since="$since" --oneline 2>$null | Measure-Object | Select-Object -ExpandProperty Count
    return $count
}

function Get-RecentChanges {
    param([string]$SinceDate)
    $since = if ($SinceDate) { $SinceDate } else { "1 week ago" }
    
    $added = 0
    $removed = 0
    
    $diff = git diff --stat --since="$since" 2>$null
    if ($diff) {
        $lines = $diff -split '\s+' | Where-Object { $_ -match '^\d+$' }
        if ($lines.Count -ge 2) {
            $added = [int]$lines[0]
            $removed = [int]$lines[1]
        }
    }
    
    return @{ Added = $added; Removed = $removed }
}

function Get-SessionInfo {
    $stateFile = Join-Path $PSScriptRoot "..\tools\.session\state.json"
    if (Test-Path $stateFile) {
        $state = Get-Content $stateFile -Raw | ConvertFrom-Json
        return $state
    }
    return $null
}

function New-PRAuditFile {
    param(
        [string]$Branch,
        [string]$Title,
        [hashtable]$Metrics
    )
    
    $timestamp = Get-Date -Format "yyyy-MM-ddTHH:mm:ss"
    $dateTag = Get-Date -Format "yyyy-MM-dd-HHmmss"
    
    $auditDir = Join-Path $projectRoot ".audit"
    $auditSubDir = Join-Path $auditDir "pr-audits"
    if (-not (Test-Path $auditSubDir)) {
        New-Item -ItemType Directory -Path $auditSubDir -Force | Out-Null
    }
    
    $auditFileName = "pr-audit_$dateTag.md"
    $auditPath = Join-Path $auditSubDir $auditFileName
    
    $auditContent = @"
# PR Audit - $dateTag

**Branch:** $Branch  
**PR Title:** $(if ($Title) { $Title } else { "N/A" })  
**Timestamp:** $timestamp  
**Project:** $(Split-Path $projectRoot -Leaf)  
**User:** $env:USERNAME@$env:COMPUTERNAME  

---

## Summary

| Metric | Value |
|--------|-------|
| Commits | $($Metrics.CommitCount) |
| Lines Added | $($Metrics.LinesAdded) |
| Lines Removed | $($Metrics.LinesRemoved) |
| Files Changed | $($Metrics.FilesChanged) |
| Development Time | $([math]::Round($Metrics.DevelopmentTimeHours, 1)) hours |

---

## Timeline

| Event | Timestamp |
|-------|-----------|
| Branch Created | $($Metrics.BranchCreated) |
| First Commit | $(if ($Metrics.FirstCommit) { $Metrics.FirstCommit } else { "N/A" }) |
| Last Commit | $(if ($Metrics.LastCommit) { $Metrics.LastCommit } else { "N/A" }) |
| PR Created | $timestamp |

---

## Quality Checks

| Check | Status |
|-------|--------|
| Pre-Push Checks | $(if ($Metrics.PrePushChecks) { '✅' } else { '❌' }) |
| Validation Passed | $(if ($Metrics.ValidationPassed) { '✅' } else { '❌' }) |
| Tests Run | $(if ($Metrics.TestsRun -gt 0) { "$($Metrics.TestsRun)" } else { "N/A" }) |
| Tests Passed | $(if ($Metrics.TestsPassed -gt 0) { "$($Metrics.TestsPassed)" } else { "N/A" }) |

---

## Commits

"@
    
    if ($Metrics.CommitCount -gt 0) {
        $commits = git log --oneline --first-parent 2>$null | Select-Object -First 10
        if ($commits) {
            $auditContent += "`n| Hash | Message |`n|------|---------|`n"
            foreach ($commit in $commits) {
                $parts = $commit -split '\s+', 2
                if ($parts.Count -ge 2) {
                    $auditContent += "| $($parts[0]) | $($parts[1]) |`n"
                }
            }
        }
    } else {
        $auditContent += "No commits recorded.`n"
    }
    
    $auditContent += @"

---

*Generated by generate-pr-artifacts.ps1*
"@
    
    $auditContent | Out-File -FilePath $auditPath -Encoding UTF8
    Write-Log "PR audit file generated: $auditPath" "OK"
    
    return $auditPath
}

function New-PRBudgetFile {
    param(
        [string]$Branch,
        [hashtable]$Metrics
    )
    
    $timestamp = Get-Date -Format "yyyy-MM-ddTHH:mm:ss"
    $dateTag = Get-Date -Format "yyyy-MM-dd-HHmmss"
    
    $auditDir = Join-Path $projectRoot ".audit"
    $budgetSubDir = Join-Path $auditDir "budgets"
    if (-not (Test-Path $budgetSubDir)) {
        New-Item -ItemType Directory -Path $budgetSubDir -Force | Out-Null
    }
    
    $budgetFileName = "pr-budget_$dateTag.json"
    $budgetPath = Join-Path $budgetSubDir $budgetFileName
    
    $costPer1MTokens = 10.0
    $costPerToken = $costPer1MTokens / 1000000
    $estimatedCost = [math]::Round($Metrics.TotalTokens * $costPerToken, 4)
    
    $budget = @{
        id = "pr-budget-$dateTag"
        type = "pr-budget"
        timestamp = $timestamp
        branch = $Branch
        project = @{
            name = Split-Path $projectRoot -Leaf
            path = $projectRoot.ToString()
        }
        period = @{
            start = $Metrics.BranchCreated
            end = $timestamp
        }
        usage = @{
            commits = $Metrics.CommitCount
            linesAdded = $Metrics.LinesAdded
            linesRemoved = $Metrics.LinesRemoved
            estimatedAITokens = $Metrics.TotalTokens
        }
        costs = @{
            costPer1MTokens = $costPer1MTokens
            estimatedCost = $estimatedCost
            currency = "USD"
        }
        budget = @{
            prBudget = 20.0
            remaining = [math]::Round(20.0 - $estimatedCost, 4)
        }
        alerts = @(
            if ($estimatedCost -gt 10.0) { 
                @{ level = "warning"; message = "PR cost exceeds $10 threshold" } 
            }
        )
    }
    
    $budget | ConvertTo-Json -Depth 10 | Out-File -FilePath $budgetPath -Encoding UTF8
    Write-Log "PR budget file generated: $budgetPath" "OK"
    
    return $budgetPath
}

function New-PRTelemetryFile {
    param(
        [string]$Branch,
        [hashtable]$Metrics
    )
    
    $timestamp = Get-Date -Format "yyyy-MM-ddTHH:mm:ss"
    $dateTag = Get-Date -Format "yyyy-MM-dd-HHmmss"
    
    $auditDir = Join-Path $projectRoot ".audit"
    $telemetrySubDir = Join-Path $auditDir "telemetry"
    if (-not (Test-Path $telemetrySubDir)) {
        New-Item -ItemType Directory -Path $telemetrySubDir -Force | Out-Null
    }
    
    $telemetryFileName = "pr-telemetry_$dateTag.json"
    $telemetryPath = Join-Path $telemetrySubDir $telemetryFileName
    
    $telemetry = @{
        id = "pr-telemetry-$dateTag"
        type = "pr-telemetry"
        timestamp = $timestamp
        branch = $Branch
        project = @{
            name = Split-Path $projectRoot -Leaf
            path = $projectRoot.ToString()
        }
        performance = @{
            developmentTimeHours = $Metrics.DevelopmentTimeHours
            commitsPerDay = [math]::Round($Metrics.CommitCount / [math]::Max($Metrics.DevelopmentTimeHours / 8, 1), 2)
            linesPerCommit = [math]::Round(($Metrics.LinesAdded + $Metrics.LinesRemoved) / [math]::Max($Metrics.CommitCount, 1), 2)
        }
        activity = @{
            commits = $Metrics.CommitCount
            filesChanged = $Metrics.FilesChanged
            linesAdded = $Metrics.LinesAdded
            linesRemoved = $Metrics.LinesRemoved
        }
        quality = @{
            validationPassed = $Metrics.ValidationPassed
            prePushChecksPassed = $Metrics.PrePushChecks
            testsPassed = $Metrics.TestsPassed
        }
        aiUsage = @{
            totalTokens = $Metrics.TotalTokens
            estimatedRequests = $Metrics.AIRequests
        }
        metadata = @{
            machineId = $env:COMPUTERNAME
            userName = $env:USERNAME
            branch = $Branch
        }
    }
    
    $telemetry | ConvertTo-Json -Depth 10 | Out-File -FilePath $telemetryPath -Encoding UTF8
    Write-Log "PR telemetry file generated: $telemetryPath" "OK"
    
    return $telemetryPath
}

function Invoke-GeneratePRArtifacts {
    param(
        [string]$Branch,
        [string]$Title
    )
    
    Write-Log "Generating PR artifacts for branch: $Branch" "INFO"
    
    if ([string]::IsNullOrWhiteSpace($Branch)) {
        $Branch = Get-CurrentBranch
    }
    
    $sessionInfo = Get-SessionInfo
    
    $changes = Get-RecentChanges
    $commitCount = Get-CommitCount
    
    $metrics = @{
        Branch = $Branch
        BranchCreated = if ($sessionInfo) { $sessionInfo.startedAt } else { (Get-Date).AddDays(-7).ToString("yyyy-MM-ddTHH:mm:ss") }
        FirstCommit = (git log --reverse --format="%ai" 2>$null | Select-Object -First 1)
        LastCommit = (git log -1 --format="%ai" 2>$null)
        CommitCount = $commitCount
        LinesAdded = $changes.Added
        LinesRemoved = $changes.Removed
        FilesChanged = (git diff --name-only 2>$null | Measure-Object | Select-Object -ExpandProperty Count)
        TotalTokens = 0
        AIRequests = 0
        DevelopmentTimeHours = 0
        PrePushChecks = $true
        ValidationPassed = $true
        TestsRun = 0
        TestsPassed = 0
    }
    
    if ($sessionInfo -and $sessionInfo.startedAt) {
        $start = [DateTime]::Parse($sessionInfo.startedAt)
        $metrics.DevelopmentTimeHours = [math]::Round(((Get-Date) - $start).TotalHours, 2)
    }
    
    $auditPath = New-PRAuditFile -Branch $Branch -Title $Title -Metrics $metrics
    $budgetPath = New-PRBudgetFile -Branch $Branch -Metrics $metrics
    $telemetryPath = New-PRTelemetryFile -Branch $Branch -Metrics $metrics
    
    Write-Log "" "INFO"
    Write-Log "PR artifacts generation completed" "OK"
    Write-Log "  Audit: $auditPath" "INFO"
    Write-Log "  Budget: $budgetPath" "INFO"
    Write-Log "  Telemetry: $telemetryPath" "INFO"
    
    return @{
        Audit = $auditPath
        Budget = $budgetPath
        Telemetry = $telemetryPath
    }
}

if ($PrePush -or $PostPush) {
    $branch = Get-CurrentBranch
    Invoke-GeneratePRArtifacts -Branch $branch -Title ""
} else {
    Write-Host "Usage: generate-pr-artifacts.ps1 [-PrePush|-PostPush]" -ForegroundColor Yellow
    Write-Host "  -PrePush   Generate artifacts before push (during PR creation)" -ForegroundColor Gray
    Write-Host "  -PostPush  Generate artifacts after push completes" -ForegroundColor Gray
    Write-Host ""
    Write-Host "Examples:" -ForegroundColor Cyan
    Write-Host "  .\generate-pr-artifacts.ps1 -PrePush" -ForegroundColor Gray
    Write-Host "  .\generate-pr-artifacts.ps1 -PostPush" -ForegroundColor Gray
}
