$ErrorActionPreference = 'Stop'

Write-Host "Workspace Foundation"
Write-Host ""
Write-Host "Quick start:"
Write-Host "  scripts\init-workspace.ps1"
Write-Host "  scripts\validate-workspace.ps1"
Write-Host "  scripts\new-project.ps1 -Name <project> -Kind service|cli|library"
Write-Host "  scripts\new-project.ps1 -Name <project> -Preset dashboard -Architecture clean -Profile web"
Write-Host "  scripts\new-project.ps1 -Name <project> -AiModelMode none|local|cloud -AiModelProvider <provider> -AiModelName <model> -AiModelEndpoint <endpoint>"
Write-Host "  scripts\new-project.ps1 -Name <project> -AiModelNotes <notes>"
Write-Host "  scripts\run-engram.ps1"
Write-Host "  scripts\clean-runtime.ps1"
Write-Host "  scripts\install-workspace-skills.ps1"
Write-Host ""
Write-Host "Project kinds:"
Write-Host "  service   backend apps, APIs, workers, dashboards"
Write-Host "  cli       command line tools and automation entrypoints"
Write-Host "  library   reusable packages and SDK-style codebases"
Write-Host ""
Write-Host "Scaffold defaults:"
Write-Host "  Defaults are safe. Use parameters only when the structure is already known."
Write-Host "  If you are unsure, keep defaults and resolve the details with the user or AI helper."
Write-Host "  Project context is written to docs\project-context.md and records architecture plus AI choices."
Write-Host ""
Write-Host "Workspace config:"
Write-Host "  config\workspace.config.json"
Write-Host "  config\workspace.portable.example.json"
Write-Host ""
Write-Host "Tools are external and not vendored."
Write-Host "The workspace skills are shipped inside the kit and installed separately into Codex."
Write-Host "Use docs\installation.md for the full step-by-step guide."
