#!/usr/bin/env pwsh
#Requires -Version 7.0
<#
.SYNOPSIS
    Install git hooks for the Foundation workspace.

.DESCRIPTION
    Creates wrapper scripts in .git/hooks/ that delegate to PowerShell
    scripts in hooks/. Safe to re-run (idempotent).

.PARAMETER Force
    Overwrite existing hooks without prompting.

.EXAMPLE
    pwsh -File tools/install-hooks.ps1
    pwsh -File tools/install-hooks.ps1 -Force
#>
param([switch]$Force)

$ErrorActionPreference = 'Stop'
$Root = Split-Path -Parent $PSScriptRoot

$HookMap = @{
    'pre-commit'   = 'hooks/pre-commit.ps1'
    'post-checkout'= 'hooks/post-checkout.ps1'
}

$GitHooksDir = Join-Path $Root '.git' 'hooks'
if (-not (Test-Path $GitHooksDir)) {
    Write-Error "Not a git repository: $Root"
    exit 1
}

$installed = 0
$skipped   = 0

foreach ($name in $HookMap.Keys) {
    $source  = $HookMap[$name]
    $target  = Join-Path $GitHooksDir $name
    $psPath  = Join-Path $Root $source

    if (-not (Test-Path $psPath)) {
        Write-Warning "Source not found, skipping: $source"
        continue
    }

    if ((Test-Path $target) -and -not $Force) {
        Write-Host "  [SKIP] $name already exists (use -Force to overwrite)" -ForegroundColor Yellow
        $skipped++
        continue
    }

    # Bash wrapper — uses cd+relative path to avoid MSYS→Windows path conversion issues
    $wrapper = @"
#!/bin/sh
# Auto-generated by tools/install-hooks.ps1 — do not edit manually
cd `"`$(git rev-parse --show-toplevel)`"
exec pwsh -NoProfile -ExecutionPolicy Bypass -File "$source" "`$@"
"@
    Set-Content -Path $target -Value $wrapper -Encoding utf8NoBOM -Force
    # Ensure executable bit on unix-like systems
    if ($IsLinux -or $IsMacOS) { & chmod +x $target }

    Write-Host "  [OK]   $name → $source" -ForegroundColor Green
    $installed++
}

Write-Host ""
Write-Host "Hooks installed: $installed  Skipped: $skipped" -ForegroundColor Cyan
if ($installed -gt 0) {
    Write-Host "Run 'git commit --dry-run' to verify." -ForegroundColor DarkGray
}
