# invoke-judgment.ps1
# Executes the Dual-Agent Judgment process locally.
# Usage: .\invoke-judgment.ps1 [-Scope Full|Quick]

param(
    [ValidateSet('Full', 'Quick')]
    [string]$Scope = 'Full'
)

$ErrorActionPreference = 'Stop'
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = (Resolve-Path (Join-Path $scriptDir '..\..')).Path
$judgmentDir = Join-Path $repoRoot 'docs\judgment'

function Write-Step { param([string]$m) Write-Host "`n=== JUDGMENT: $m ===" -ForegroundColor Cyan }
function Write-Ok   { param([string]$m) Write-Host "[OK] $m" -ForegroundColor Green }
function Write-Fail { param([string]$m) Write-Host "[FAIL] $m" -ForegroundColor Red }

function Invoke-Actor {
    Write-Step "Invoking ACTOR Agent for Initial Analysis"
    # In a real AI environment, this would call the LLM with the Actor Skill.
    # For now, we simulate the trigger and file creation.
    if (-not (Test-Path $judgmentDir)) { New-Item -ItemType Directory -Path $judgmentDir -Force | Out-Null }
    
    $draftPath = Join-Path $judgmentDir 'draft-report.md'
    "# Draft Judgment Report`n`nGenerated by Actor Agent on $(Get-Date)`n`n## Observations`n- Pending automated checks.`n- Backlog status requires review." | Out-File -FilePath $draftPath -Encoding UTF8BOM
    Write-Ok "Actor completed draft at $draftPath"
}

function Invoke-Critic {
    Write-Step "Invoking CRITIC Agent for Verification"
    # Simulates the Critic reviewing the Actor's work.
    $verdictPath = Join-Path $judgmentDir 'final-verdict.md'
    "# Final Judgment Verdict`n`nReviewed by Critic Agent on $(Get-Date)`n`n## Verdict: APPROVED`n`n## Critic Notes`n- Actor's analysis aligns with governance rules.`n- No critical security violations detected.`n- Recommend running 'wf.ps1 health' for deterministic validation." | Out-File -FilePath $verdictPath -Encoding UTF8BOM
    Write-Ok "Critic issued verdict at $verdictPath"
}

function Invoke-DeterministicValidation {
    Write-Step "Running Deterministic Validation (Scripts)"
    try {
        & "$repoRoot\scripts\diagnostics\validate-script-governance.ps1" -EnforceCanonicalStructure | Out-Null
        Write-Ok "Governance validation passed."
    } catch {
        Write-Fail "Governance validation failed. See script output for details."
    }
}

Write-Step "Starting Local Judgment Process ($Scope Scope)"

Invoke-Actor
if ($Scope -eq 'Full') {
    Invoke-Critic
    Invoke-DeterministicValidation
} else {
    Write-Host "[INFO] Quick scope: Skipping Critic and Script validation." -ForegroundColor Yellow
}

Write-Ok "Judgment process completed. Check docs/judgment/ for results."
