# invoke-judgment.ps1
# Executes the Dual-Agent Judgment process locally with recursive remediation.
# Usage: .\invoke-judgment.ps1 [-Scope Full|Quick] [-Remediate] [-MaxIterations 3]

param(
    [ValidateSet('Full', 'Quick')]
    [string]$Scope = 'Full',
    
    [switch]$Remediate,
    
    [int]$MaxIterations = 3
)

$ErrorActionPreference = 'Stop'
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = (Resolve-Path (Join-Path $scriptDir '..\..')).Path
$judgmentDir = Join-Path $repoRoot 'docs\judgment'
$configFile = Join-Path $repoRoot 'config\workspace.config.json'

function Write-Step { param([string]$m) Write-Host "`n=== JUDGMENT: $m ===" -ForegroundColor Cyan }
function Write-Ok   { param([string]$m) Write-Host "[OK] $m" -ForegroundColor Green }
function Write-Fail { param([string]$m) Write-Host "[FAIL] $m" -ForegroundColor Red }
function Write-Warn { param([string]$m) Write-Host "[WARN] $m" -ForegroundColor Yellow }

function Invoke-Actor {
    Write-Step "Invoking ACTOR Agent for Initial Analysis"
    if (-not (Test-Path $judgmentDir)) { New-Item -ItemType Directory -Path $judgmentDir -Force | Out-Null }
    
    $draftPath = Join-Path $judgmentDir 'draft-report.md'
    "# Draft Judgment Report`n`nGenerated by Actor Agent on $(Get-Date)`n`n## Observations`n- Pending automated checks.`n- Backlog status requires review." | Out-File -FilePath $draftPath -Encoding UTF8BOM
    Write-Ok "Actor completed draft at $draftPath"
}

function Invoke-Critic {
    Write-Step "Invoking CRITIC Agent for Verification"
    $verdictPath = Join-Path $judgmentDir 'final-verdict.md'
    
    # Simulate Critic Logic (In production, this calls the LLM)
    $validationPassed = $true
    try {
        & "$repoRoot\scripts\diagnostics\validate-script-governance.ps1" -EnforceCanonicalStructure | Out-Null
    } catch {
        $validationPassed = $false
    }

    if ($validationPassed) {
        "# Final Judgment Verdict`n`nReviewed by Critic Agent on $(Get-Date)`n`n## Verdict: APPROVED`n`n## Critic Notes`n- All governance checks passed.`n- System is healthy." | Out-File -FilePath $verdictPath -Encoding UTF8BOM
        Write-Ok "Critic Verdict: APPROVED"
        return $true
    } else {
        "# Final Judgment Verdict`n`nReviewed by Critic Agent on $(Get-Date)`n`n## Verdict: REJECTED`n`n## Critic Notes`n- Governance validation failed.`n- Action required: Run remediation." | Out-File -FilePath $verdictPath -Encoding UTF8BOM
        Write-Fail "Critic Verdict: REJECTED"
        return $false
    }
}

function Invoke-Remediation {
    Write-Step "Invoking REMEDIATOR Agent (Attempt $currentIter/$MaxIterations)"
    $remediationPath = Join-Path $judgmentDir 'remediation-report.md'
    "# Remediation Report`n`nAttempt: $currentIter`nAction: Attempting automated fixes and fallback preparation." | Out-File -FilePath $remediationPath -Encoding UTF8BOM
    
    # Try Self-Healing (Simulated)
    Write-Host "[INFO] Attempting self-healing of tools..." -ForegroundColor Gray
    # In a real scenario, this would call 'go install' or 'npm install' based on config
}

Write-Step "Starting Local Judgment Process ($Scope Scope)"

Invoke-Actor

if ($Scope -eq 'Full') {
    $isApproved = Invoke-Critic
    
    if (-not $isApproved -and $Remediate) {
        $currentIter = 1
        while (-not $isApproved -and $currentIter -le $MaxIterations) {
            Invoke-Remediation
            $isApproved = Invoke-Critic
            $currentIter++
        }
        
        if (-not $isApproved) {
            Write-Warn "Judgment stuck after $MaxIterations iterations. Manual recovery required."
            Write-Host "Run: .\scripts\utilities\manual-recovery.ps1" -ForegroundColor Red
        }
    }
} else {
    Write-Host "[INFO] Quick scope: Skipping Critic and Remediation." -ForegroundColor Yellow
}

Write-Ok "Judgment process completed. Check docs/judgment/ for results."
