# generate-session-review.ps1 (Foundation Core)
# Agnostic session review generator for AI-assisted change control.

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectRoot = Resolve-Path (Join-Path $scriptDir "..")
Set-Location $projectRoot

# Verify if the directory is a Git repository before proceeding
git rev-parse --is-inside-work-tree 2>$null
if ($LASTEXITCODE -ne 0) {
    Write-Host "INFO: No Git repository detected. Skipping session report generation." -ForegroundColor Gray
    exit 0
}

$headRef = git show-ref --head HEAD 2>$null
if ($headRef) {
    $lastCommit = git rev-parse HEAD 2>$null
} else {
    Write-Host "No previous commit detected. Initializing initial session report."
    $lastCommit = "Initial"
}

# Capture current changes (staged and unstaged) for the session report
$changedFilesOutput = git status --porcelain 2>$null
$changedFiles = $changedFilesOutput | ForEach-Object { 
    if ($_.Length -gt 3) { $_.Substring(3) }
} | Where-Object { $_ -ne "" }

if ($changedFiles.Count -eq 0 -and $lastCommit -ne "Initial") {
    Write-Host "No changes detected to report in this session."
    exit 0
}

$date = Get-Date -Format "yyyy-MM-dd"
$reviewDir = Join-Path $projectRoot "docs/code-reviews"
if (-not (Test-Path $reviewDir)) {
    New-Item -ItemType Directory -Path $reviewDir -Force | Out-Null
}

$reviewFile = Join-Path $reviewDir "${date}-session-review.md"

$contentLines = @()
$contentLines += "# Code Review: Session Changes - $date"
$contentLines += ""
$contentLines += "### IMPORTANT"
$contentLines += "This document is the persistent memory of Engram for this session."
$contentLines += ""
$contentLines += "**Fecha:** $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
$contentLines += "**Reviewer:** Engram AI Agent"
$currentBranch = git rev-parse --abbrev-ref HEAD 2>$null
if ($LASTEXITCODE -ne 0) { $currentBranch = "Initial" }
$contentLines += "**Base Branch:** $currentBranch"
$contentLines += ""
$contentLines += "## Changed Files"
$contentLines += ""
foreach ($file in $changedFiles) { $contentLines += "- $file" }
if ($changedFiles.Count -eq 0) { $contentLines += "- No modified files (Initial commit)" }

$contentLines += ""
$contentLines += "## Architecture and Quality Analysis"
$contentLines += ""
$contentLines += "[Automatic agent analysis on project integrity]"
$contentLines += ""
$contentLines += "## Validation Checklist"
$contentLines += ""
$contentLines += "- [ ] Code complies with Gentleman Programming standards"
$contentLines += "- [ ] No secrets or credentials exposed"
$contentLines += "- [ ] Base architecture remains intact"
$contentLines += "- [ ] Documentation updated"
$contentLines += ""
$contentLines += "---"
$contentLines += "*Report generated by Workspace Foundation Core.*"

$contentLines -join "`n" | Out-File -FilePath $reviewFile -Encoding UTF8
Write-Host "SUCCESS: Session review generated at: $reviewFile" -ForegroundColor Green