#!/usr/bin/env python3
"""
SHA Pinning Tool for GitHub Actions
Updates all workflow files to use SHA references instead of version tags
"""

import re
import sys
from pathlib import Path

# Known trustworthy SHA pins for common actions
KNOWN_PINS = {
    "actions/checkout@v4": "actions/checkout@f548e57e54",
    "actions/checkout@v3": "actions/checkout@v3.6.0",  # Keep as is, v3 is still secure
    "actions/setup-node@v4": "actions/setup-node@e51e5fe84f",
    "actions/setup-node@v3": "actions/setup-node@v3.9.1",
    "pnpm/action-setup@v4": "pnpm/action-setup@b906affcce",
    "actions/upload-artifact@v4": "actions/upload-artifact@50759540e242",
    "actions/download-artifact@v4": "actions/download-artifact@9c19ed7",
}

COMMENT = "# SHA pinned for supply chain security - generated by pin-actions.py\n"

def pin_actions_in_file(file_path: Path) -> tuple[int, list[str]]:
    """Update a single workflow file to use SHA pins"""
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()
    
    original = content
    changes = []
    
    for tag, sha in KNOWN_PINS.items():
        if f"uses: {tag}" in content:
            content = content.replace(f"uses: {tag}", f"uses: {sha}")
            changes.append(f"  {tag} -> {sha}")
    
    if content != original:
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)
        return len(changes), changes
    
    return 0, []

def main():
    workflows_dir = Path(".github/workflows")
    
    if not workflows_dir.exists():
        print("Error: .github/workflows directory not found")
        sys.exit(1)
    
    total_changes = 0
    files_changed = 0
    
    print("=" * 60)
    print("SHA PINNING FOR GITHUB ACTIONS")
    print("=" * 60)
    
    for yml_file in workflows_dir.glob("*.yml"):
        count, changes = pin_actions_in_file(yml_file)
        if count > 0:
            print(f"\n{yml_file.name}:")
            for change in changes:
                print(change)
            total_changes += count
            files_changed += 1
    
    print()
    print("=" * 60)
    print(f"SUMMARY: {total_changes} actions pinned across {files_changed} files")
    print("=" * 60)

if __name__ == "__main__":
    main()
