<#
.SYNOPSIS
    Report Generator - Generate centralized telemetry reports
    
.DESCRIPTION
    Generates comprehensive reports from distributed tracing data:
    - Daily summaries
    - Performance analysis
    - Error analysis
    - Dispatch metrics
    - System health reports
    
.NOTES
    Author: gentleman-programming
    Version: 1.0
#>

# ============================================================================
# REPORT GENERATION
# ============================================================================

function Generate-DailyReport {
    <#
    .SYNOPSIS
        Generate daily telemetry report
    #>
    param(
        [DateTime]$Date = (Get-Date),
        [string]$OutputPath = ".telemetry/reports",
        [string]$SessionId = $null
    )
    
    $dateStr = $Date.ToString("yyyy-MM-dd")
    $reportFile = "$OutputPath/daily-summary-$dateStr.md"
    
    # Collect data
    $tracesDir = ".telemetry/traces"
    $metricsDir = ".telemetry/metrics"
    
    $traceFiles = @()
    if (Test-Path $tracesDir) {
        $traceFiles = Get-ChildItem -Path $tracesDir -Filter "*-traces-$dateStr.jsonl" -ErrorAction SilentlyContinue
    }
    
    $metricsFiles = @()
    if (Test-Path $metricsDir) {
        $metricsFiles = Get-ChildItem -Path $metricsDir -Filter "metrics-$dateStr.json" -ErrorAction SilentlyContinue
    }
    
    # Parse traces
    $allTraces = @()
    foreach ($file in $traceFiles) {
        $content = Get-Content -Path $file.FullName -Raw
        $lines = $content -split "`n" | Where-Object { $_ -match '\S' }
        foreach ($line in $lines) {
            try {
                $trace = $line | ConvertFrom-Json
                $allTraces += $trace
            }
            catch {
                # Skip malformed lines
            }
        }
    }
    
    # Parse metrics
    $allMetrics = @()
    foreach ($file in $metricsFiles) {
        try {
            $metricsData = Get-Content -Path $file.FullName | ConvertFrom-Json
            $allMetrics += $metricsData.Metrics
        }
        catch {
            # Skip malformed files
        }
    }
    
    # Generate report
    $report = @"
# Daily Telemetry Report - $dateStr

## Executive Summary

- **Report Date**: $dateStr
- **Generated**: $(Get-Date -Format "o")
- **Total Traces**: $($allTraces.Count)
- **Total Metrics**: $($allMetrics.Count)

## Trace Statistics

"@
    
    # Trace breakdown by type
    $tracesByType = $allTraces | Group-Object -Property SpanType
    $report += "`n### Traces by Type`n`n"
    $report += "| Type | Count | Avg Duration (ms) |`n"
    $report += "|------|-------|-------------------|`n"
    
    foreach ($group in $tracesByType) {
        $avgDuration = ($group.Group | Measure-Object -Property Duration -Average).Average
        $report += "| $($group.Name) | $($group.Count) | $([Math]::Round($avgDuration, 2)) |`n"
    }
    
    # Status breakdown
    $report += "`n### Traces by Status`n`n"
    $statusBreakdown = $allTraces | Group-Object -Property Status
    $report += "| Status | Count | Percentage |`n"
    $report += "|--------|-------|------------|`n"
    
    foreach ($group in $statusBreakdown) {
        $percentage = [Math]::Round(($group.Count / $allTraces.Count) * 100, 2)
        $report += "| $($group.Name) | $($group.Count) | $percentage% |`n"
    }
    
    # Performance metrics
    $report += "`n## Performance Metrics`n`n"
    
    if ($allTraces.Count -gt 0) {
        $avgDuration = ($allTraces | Measure-Object -Property Duration -Average).Average
        $maxDuration = ($allTraces | Measure-Object -Property Duration -Maximum).Maximum
        $minDuration = ($allTraces | Measure-Object -Property Duration -Minimum).Minimum
        
        $report += "- **Average Span Duration**: $([Math]::Round($avgDuration, 2)) ms`n"
        $report += "- **Max Span Duration**: $([Math]::Round($maxDuration, 2)) ms`n"
        $report += "- **Min Span Duration**: $([Math]::Round($minDuration, 2)) ms`n"
    }
    
    # Error analysis
    $errorTraces = $allTraces | Where-Object { $_.Status -eq "error" }
    if ($errorTraces.Count -gt 0) {
        $report += "`n## Error Analysis`n`n"
        $report += "- **Total Errors**: $($errorTraces.Count)`n"
        $report += "- **Error Rate**: $([Math]::Round(($errorTraces.Count / $allTraces.Count) * 100, 2))%`n"
        
        $report += "`n### Error Details`n`n"
        $errorsByName = $errorTraces | Group-Object -Property Name
        foreach ($group in $errorsByName) {
            $report += "- **$($group.Name)**: $($group.Count) errors`n"
        }
    }
    
    $report += "`n---`n"
    $report += "Generated by Distributed Tracing System`n"
    
    # Save report
    $report | Set-Content -Path $reportFile -Encoding UTF8
    
    Write-Host "[REPORT] Daily report generated: $reportFile" -ForegroundColor Green
    return $reportFile
}

function Generate-PerformanceAnalysis {
    <#
    .SYNOPSIS
        Generate performance analysis report
    #>
    param(
        [DateTime]$Date = (Get-Date),
        [string]$OutputPath = ".telemetry/reports",
        [int]$TopN = 10
    )
    
    $dateStr = $Date.ToString("yyyy-MM-dd")
    $reportFile = "$OutputPath/performance-analysis-$dateStr.md"
    
    # Collect traces
    $tracesDir = ".telemetry/traces"
    $allTraces = @()
    
    if (Test-Path $tracesDir) {
        $traceFiles = Get-ChildItem -Path $tracesDir -Filter "*-traces-$dateStr.jsonl" -ErrorAction SilentlyContinue
        
        foreach ($file in $traceFiles) {
            $content = Get-Content -Path $file.FullName -Raw
            $lines = $content -split "`n" | Where-Object { $_ -match '\S' }
            foreach ($line in $lines) {
                try {
                    $trace = $line | ConvertFrom-Json
                    $allTraces += $trace
                }
                catch {
                    # Skip malformed lines
                }
            }
        }
    }
    
    $report = @"
# Performance Analysis Report - $dateStr

## Overview

- **Report Date**: $dateStr
- **Generated**: $(Get-Date -Format "o")
- **Total Spans Analyzed**: $($allTraces.Count)

## Top $TopN Slowest Operations

"@
    
    $slowestOps = $allTraces | Sort-Object -Property Duration -Descending | Select-Object -First $TopN
    $report += "`n| Rank | Operation | Duration (ms) | Status |`n"
    $report += "|------|-----------|---------------|--------|`n"
    
    for ($i = 0; $i -lt $slowestOps.Count; $i++) {
        $op = $slowestOps[$i]
        $report += "| $($i + 1) | $($op.Name) | $([Math]::Round($op.Duration, 2)) | $($op.Status) |`n"
    }
    
    # Throughput analysis
    $report += "`n## Throughput Analysis`n`n"
    
    $successTraces = $allTraces | Where-Object { $_.Status -eq "success" }
    $errorTraces = $allTraces | Where-Object { $_.Status -eq "error" }
    
    $report += "- **Successful Operations**: $($successTraces.Count)`n"
    $report += "- **Failed Operations**: $($errorTraces.Count)`n"
    $report += "- **Success Rate**: $([Math]::Round(($successTraces.Count / $allTraces.Count) * 100, 2))%`n"
    
    # Bottleneck analysis
    $report += "`n## Bottleneck Analysis`n`n"
    
    $bottlenecks = $allTraces | Group-Object -Property Name | ForEach-Object {
        @{
            Name = $_.Name
            Count = $_.Count
            AvgDuration = ($_.Group | Measure-Object -Property Duration -Average).Average
        }
    } | Sort-Object -Property AvgDuration -Descending | Select-Object -First 5
    
    $report += "| Operation | Frequency | Avg Duration (ms) |`n"
    $report += "|-----------|-----------|-------------------|`n"
    
    foreach ($bottleneck in $bottlenecks) {
        $report += "| $($bottleneck.Name) | $($bottleneck.Count) | $([Math]::Round($bottleneck.AvgDuration, 2)) |`n"
    }
    
    $report += "`n---`n"
    $report += "Generated by Distributed Tracing System`n"
    
    # Save report
    $report | Set-Content -Path $reportFile -Encoding UTF8
    
    Write-Host "[REPORT] Performance analysis generated: $reportFile" -ForegroundColor Green
    return $reportFile
}

function Generate-ErrorAnalysis {
    <#
    .SYNOPSIS
        Generate error analysis report
    #>
    param(
        [DateTime]$Date = (Get-Date),
        [string]$OutputPath = ".telemetry/reports"
    )
    
    $dateStr = $Date.ToString("yyyy-MM-dd")
    $reportFile = "$OutputPath/error-analysis-$dateStr.md"
    
    # Collect error traces
    $tracesDir = ".telemetry/traces"
    $errorTraces = @()
    
    if (Test-Path $tracesDir) {
        $traceFiles = Get-ChildItem -Path $tracesDir -Filter "*-traces-$dateStr.jsonl" -ErrorAction SilentlyContinue
        
        foreach ($file in $traceFiles) {
            $content = Get-Content -Path $file.FullName -Raw
            $lines = $content -split "`n" | Where-Object { $_ -match '\S' }
            foreach ($line in $lines) {
                try {
                    $trace = $line | ConvertFrom-Json
                    if ($trace.Status -eq "error") {
                        $errorTraces += $trace
                    }
                }
                catch {
                    # Skip malformed lines
                }
            }
        }
    }
    
    $report = @"
# Error Analysis Report - $dateStr

## Summary

- **Report Date**: $dateStr
- **Generated**: $(Get-Date -Format "o")
- **Total Errors**: $($errorTraces.Count)

"@
    
    if ($errorTraces.Count -eq 0) {
        $report += "**Status**: No errors detected ✓`n"
    }
    else {
        # Errors by type
        $report += "## Errors by Operation Type`n`n"
        $errorsByType = $errorTraces | Group-Object -Property SpanType
        
        $report += "| Type | Count |`n"
        $report += "|------|-------|`n"
        
        foreach ($group in $errorsByType) {
            $report += "| $($group.Name) | $($group.Count) |`n"
        }
        
        # Errors by operation
        $report += "`n## Errors by Operation`n`n"
        $errorsByName = $errorTraces | Group-Object -Property Name | Sort-Object -Property Count -Descending
        
        $report += "| Operation | Count |`n"
        $report += "|-----------|-------|`n"
        
        foreach ($group in $errorsByName) {
            $report += "| $($group.Name) | $($group.Count) |`n"
        }
        
        # Error details
        $report += "`n## Error Details`n`n"
        
        foreach ($error in $errorTraces | Select-Object -First 20) {
            $report += "### $($error.Name)`n"
            $report += "- **Time**: $($error.StartTime)`n"
            $report += "- **Duration**: $([Math]::Round($error.Duration, 2)) ms`n"
            if ($error.ErrorMessage) {
                $report += "- **Message**: $($error.ErrorMessage)`n"
            }
            $report += "`n"
        }
    }
    
    $report += "`n---`n"
    $report += "Generated by Distributed Tracing System`n"
    
    # Save report
    $report | Set-Content -Path $reportFile -Encoding UTF8
    
    Write-Host "[REPORT] Error analysis generated: $reportFile" -ForegroundColor Green
    return $reportFile
}

function Generate-DispatchMetricsReport {
    <#
    .SYNOPSIS
        Generate dispatch-specific metrics report
    #>
    param(
        [DateTime]$Date = (Get-Date),
        [string]$OutputPath = ".telemetry/reports"
    )
    
    $dateStr = $Date.ToString("yyyy-MM-dd")
    $reportFile = "$OutputPath/dispatch-metrics-$dateStr.md"
    
    # Collect dispatch traces
    $tracesDir = ".telemetry/traces"
    $dispatchTraces = @()
    
    if (Test-Path "$tracesDir/dispatch-traces-$dateStr.jsonl") {
        $content = Get-Content -Path "$tracesDir/dispatch-traces-$dateStr.jsonl" -Raw
        $lines = $content -split "`n" | Where-Object { $_ -match '\S' }
        foreach ($line in $lines) {
            try {
                $trace = $line | ConvertFrom-Json
                $dispatchTraces += $trace
            }
            catch {
                # Skip malformed lines
            }
        }
    }
    
    $report = @"
# Dispatch Metrics Report - $dateStr

## Summary

- **Report Date**: $dateStr
- **Generated**: $(Get-Date -Format "o")
- **Total Dispatches**: $($dispatchTraces.Count)

"@
    
    if ($dispatchTraces.Count -gt 0) {
        $successCount = ($dispatchTraces | Where-Object { $_.Status -eq "success" }).Count
        $errorCount = ($dispatchTraces | Where-Object { $_.Status -eq "error" }).Count
        $avgDuration = ($dispatchTraces | Measure-Object -Property Duration -Average).Average
        
        $report += "- **Successful Dispatches**: $successCount`n"
        $report += "- **Failed Dispatches**: $errorCount`n"
        $report += "- **Success Rate**: $([Math]::Round(($successCount / $dispatchTraces.Count) * 100, 2))%`n"
        $report += "- **Average Duration**: $([Math]::Round($avgDuration, 2)) ms`n"
        
        # Dispatch breakdown
        $report += "`n## Dispatch Breakdown`n`n"
        $dispatchByName = $dispatchTraces | Group-Object -Property Name
        
        $report += "| Dispatch Type | Count | Avg Duration (ms) | Success Rate |`n"
        $report += "|---------------|-------|-------------------|--------------|`n"
        
        foreach ($group in $dispatchByName) {
            $groupAvg = ($group.Group | Measure-Object -Property Duration -Average).Average
            $groupSuccess = ($group.Group | Where-Object { $_.Status -eq "success" }).Count
            $groupSuccessRate = [Math]::Round(($groupSuccess / $group.Count) * 100, 2)
            
            $report += "| $($group.Name) | $($group.Count) | $([Math]::Round($groupAvg, 2)) | $groupSuccessRate% |`n"
        }
    }
    
    $report += "`n---`n"
    $report += "Generated by Distributed Tracing System`n"
    
    # Save report
    $report | Set-Content -Path $reportFile -Encoding UTF8
    
    Write-Host "[REPORT] Dispatch metrics report generated: $reportFile" -ForegroundColor Green
    return $reportFile
}

function Generate-AllReports {
    <#
    .SYNOPSIS
        Generate all available reports for a date
    #>
    param(
        [DateTime]$Date = (Get-Date),
        [string]$OutputPath = ".telemetry/reports"
    )
    
    Write-Host "[REPORT] Generating all reports for $($Date.ToString('yyyy-MM-dd'))..." -ForegroundColor Cyan
    
    $reports = @()
    $reports += Generate-DailyReport -Date $Date -OutputPath $OutputPath
    $reports += Generate-PerformanceAnalysis -Date $Date -OutputPath $OutputPath
    $reports += Generate-ErrorAnalysis -Date $Date -OutputPath $OutputPath
    $reports += Generate-DispatchMetricsReport -Date $Date -OutputPath $OutputPath
    
    Write-Host "[REPORT] All reports generated successfully" -ForegroundColor Green
    
    return $reports
}

function Get-ReportIndex {
    <#
    .SYNOPSIS
        Get index of all available reports
    #>
    param(
        [string]$OutputPath = ".telemetry/reports"
    )
    
    $reports = @()
    
    if (Test-Path $OutputPath) {
        $reportFiles = Get-ChildItem -Path $OutputPath -Filter "*.md" -ErrorAction SilentlyContinue
        
        foreach ($file in $reportFiles) {
            $reports += @{
                Name = $file.Name
                Path = $file.FullName
                Created = $file.CreationTime
                Modified = $file.LastWriteTime
                Size = $file.Length
            }
        }
    }
    
    return $reports | Sort-Object -Property Modified -Descending
}

function Show-ReportIndex {
    <#
    .SYNOPSIS
        Display report index
    #>
    param(
        [string]$OutputPath = ".telemetry/reports"
    )
    
    $reports = Get-ReportIndex -OutputPath $OutputPath
    
    Write-Host "`n=== Available Reports ===" -ForegroundColor Cyan
    Write-Host "Location: $OutputPath`n" -ForegroundColor Gray
    
    if ($reports.Count -eq 0) {
        Write-Host "No reports found." -ForegroundColor Yellow
    }
    else {
        $reports | Format-Table -Property @(
            @{ Label = "Report"; Expression = { $_.Name } },
            @{ Label = "Modified"; Expression = { $_.Modified.ToString("yyyy-MM-dd HH:mm:ss") } },
            @{ Label = "Size"; Expression = { "$([Math]::Round($_.Size / 1KB, 2)) KB" } }
        ) -AutoSize
    }
    
    Write-Host "`n" -ForegroundColor Cyan
}

# Export functions
Export-ModuleMember -Function @(
    'Generate-DailyReport',
    'Generate-PerformanceAnalysis',
    'Generate-ErrorAnalysis',
    'Generate-DispatchMetricsReport',
    'Generate-AllReports',
    'Get-ReportIndex',
    'Show-ReportIndex'
)